import { useEffect, useState, useRef } from 'react';
import { Link } from 'react-router-dom';
const API_URL = import.meta.env.VITE_CAPRA_API_URL || 'https://caprab.cariara.com';
import { getAuthHeaders } from '../../../utils/authHeaders.js';
import { MermaidDiagram } from '../../lumora/interview/MermaidDiagram';
import { useCloudFormatter } from '../../../hooks/useCloudFormatter.ts';
import CloudProviderSelector from '../../shared/CloudProviderSelector.tsx';
import { SectionCard } from '../ui';
import { resolvePreGeneratedDiagram } from '../../../lib/preGeneratedDiagrams.ts';


/**
 * Cloud Architecture Diagram Component
 * Displays PNG diagrams generated by the Python diagrams library
 */
function CloudArchitectureDiagram({
  imageUrl,
  expanded = false,
  loading = false,
  error = null,
  cloudProvider = 'auto'
}) {
  const [imageError, setImageError] = useState(false);

  useEffect(() => {
    if (imageUrl) {
      setImageError(false);
    }
  }, [imageUrl]);

  if (loading) {
    return (
      <div className={`p-3 rounded bg-[var(--bg-elevated)] border border-[var(--border)] text-center ${expanded ? 'min-h-[400px]' : ''}`}>
        <div className="flex flex-col items-center justify-center gap-2">
          <svg className="w-5 h-5 animate-spin text-brand-400" fill="none" viewBox="0 0 24 24">
            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
          </svg>
          <div>
            <p className="text-xs text-[var(--text-primary)] font-medium">Generating diagram...</p>
            <p className="text-xs text-[var(--text-muted)]">{cloudProvider.toUpperCase()}</p>
          </div>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="p-2 rounded bg-error-500/10 border border-error-500/30">
        <p className="text-xs text-error-400">{error}</p>
      </div>
    );
  }

  if (!imageUrl || imageError) {
    return (
      <div className="text-center py-4 text-[var(--text-muted)]">
        <svg className="w-8 h-8 mx-auto mb-2 text-[var(--text-muted)]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M3 15a4 4 0 004 4h9a5 5 0 10-.1-9.999 5.002 5.002 0 10-9.78 2.096A4.001 4.001 0 003 15z" />
        </svg>
        <p className="text-xs">Click Generate for cloud architecture</p>
        <p className="text-xs text-[var(--text-muted)]">AWS/GCP/Azure icons</p>
        {imageError && <p className="text-xs text-error-400 mt-0.5">Image failed to load</p>}
      </div>
    );
  }

  return (
    <div className={`rounded overflow-hidden border border-[var(--border)] bg-[var(--bg-elevated)] flex justify-center ${expanded ? 'p-4' : 'p-4'}`}>
      <img
        src={imageUrl}
        alt="Cloud Architecture Diagram"
        className={`h-auto object-contain ${expanded ? 'max-h-[80vh] max-w-full' : 'max-w-full'}`}
        onError={(e) => {
          console.error('[CloudDiagram] Image load error:', imageUrl, e);
          setImageError(true);
        }}
      />
    </div>
  );
}

// Modal component for full-screen diagram view
function DiagramModal({ isOpen, onClose, title, children }) {
  // Handle ESC key to close modal
  useEffect(() => {
    if (!isOpen) return;

    const handleKeyDown = (e) => {
      if (e.key === 'Escape') {
        e.preventDefault();
        e.stopPropagation();
        onClose();
      }
    };

    document.addEventListener('keydown', handleKeyDown, true);
    return () => document.removeEventListener('keydown', handleKeyDown, true);
  }, [isOpen, onClose]);

  if (!isOpen) return null;

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-sm"
      onClick={onClose}
    >
      <div
        className="relative bg-[var(--bg-surface)] rounded-2xl shadow-2xl w-[95vw] h-[90vh] flex flex-col border border-[var(--border)]"
        onClick={e => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between px-4 py-3 border-b border-[var(--border)] bg-[var(--bg-elevated)]">
          <h3 className="text-sm font-semibold text-[var(--text-primary)] uppercase tracking-wide">
            {title}
          </h3>
          <button
            onClick={onClose}
            className="p-2 rounded-lg bg-[var(--bg-elevated)] hover:bg-[var(--bg-elevated)] transition-colors"
            title="Close (ESC)"
          >
            <svg className="w-5 h-5 text-[var(--text-primary)] hover:text-[var(--text-primary)]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>
        {/* Content */}
        <div className="flex-1 overflow-auto p-4 flex items-center justify-center bg-[var(--bg-surface)]">
          {children}
        </div>
      </div>
    </div>
  );
}

// Collapsible section component
function CollapsibleSection({ title, icon, color, children, defaultOpen = true, badge }) {
  const [isOpen, setIsOpen] = useState(defaultOpen);

  return (
    <div className="rounded-lg bg-[var(--bg-surface)] border border-[var(--border)] overflow-hidden">
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="w-full px-3 py-2 flex items-center justify-between hover:bg-[var(--bg-elevated)]/30 transition-colors"
      >
        <span className="text-xs font-semibold uppercase tracking-wide flex items-center gap-2 text-[var(--text-secondary)]">
          {title}
          {badge && <span className="px-1.5 py-0.5 bg-brand-400/10 text-brand-400 border border-brand-400/30 rounded text-xs font-medium">{badge}</span>}
        </span>
        <svg
          className={`w-3.5 h-3.5 text-[var(--text-muted)] transition-transform ${isOpen ? 'rotate-180' : ''}`}
          fill="none"
          stroke="currentColor"
          viewBox="0 0 24 24"
        >
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
        </svg>
      </button>
      {isOpen && <div className="px-3 pb-3 pt-1">{children}</div>}
    </div>
  );
}

/**
 * ASCII Architecture Diagram Component - Left-to-Right Flow
 */
function ASCIIDiagram({ systemDesign, detailed = false }) {
  if (!systemDesign?.included) return null;

  const str = (val) => {
    if (typeof val === 'string') return val;
    if (typeof val === 'object' && val !== null) {
      return val.step || val.description || val.name || val.tech || JSON.stringify(val);
    }
    return String(val || '');
  };

  const techStack = (systemDesign.techJustifications?.map(t => str(t.tech || t)) || []).filter(Boolean);
  const components = (systemDesign.architecture?.components || []).map(str).filter(Boolean);

  const uniqueItems = [...new Set([...components, ...techStack])];

  const categorize = (items) => {
    const tiers = { client: [], edge: [], gateway: [], compute: [], cache: [], database: [], storage: [], queue: [] };
    const patterns = {
      client: /client|browser|mobile|app|user|frontend|web\s?app/i,
      edge: /cdn|cloudfront|cloudflare|edge|akamai/i,
      gateway: /load.?balancer|alb|nlb|elb|api.?gateway|nginx|haproxy|gateway|ingress/i,
      compute: /ec2|ecs|eks|gke|aks|lambda|function|container|server|service|k8s|kubernetes|fargate|worker|encoding|base62/i,
      cache: /redis|cache|memcache|elasticache/i,
      database: /database|db|rds|aurora|dynamo|postgres|mysql|mongo|sql|cockroach/i,
      storage: /s3|storage|gcs|blob|file|bucket|object/i,
      queue: /queue|sqs|sns|kafka|kinesis|pubsub|rabbit|event|stream|message/i
    };
    items.forEach(item => {
      const itemStr = str(item);
      if (!itemStr) return;
      let matched = false;
      for (const [tier, pattern] of Object.entries(patterns)) {
        if (pattern.test(itemStr)) {
          if (!tiers[tier].includes(itemStr)) tiers[tier].push(itemStr);
          matched = true;
          break;
        }
      }
      if (!matched && !tiers.compute.includes(itemStr)) tiers.compute.push(itemStr);
    });
    return tiers;
  };

  const tiers = categorize(uniqueItems);

  // Build LEFT-TO-RIGHT ASCII diagram
  const buildASCII = () => {
    const lines = [];
    const boxW = 18; // Wider boxes

    const makeBox = (label, w = boxW) => {
      const t = label.substring(0, w - 2);
      const pad = Math.floor((w - 2 - t.length) / 2);
      return [
        '┌' + '─'.repeat(w - 2) + '┐',
        '│' + ' '.repeat(pad) + t + ' '.repeat(w - 2 - pad - t.length) + '│',
        '└' + '─'.repeat(w - 2) + '┘'
      ];
    };

    const arrow = ' ════► ';

    // Build component boxes
    const boxes = [];

    // Client
    boxes.push({ label: '👤 Client', tier: 'client' });

    // Edge/CDN
    if (tiers.edge.length > 0) boxes.push({ label: tiers.edge[0].substring(0, 14), tier: 'edge' });

    // Gateway/LB
    if (tiers.gateway.length > 0) boxes.push({ label: tiers.gateway[0].substring(0, 14), tier: 'gateway' });

    // Compute services
    tiers.compute.slice(0, detailed ? 2 : 1).forEach(c => {
      boxes.push({ label: c.substring(0, 14), tier: 'compute' });
    });

    // Cache
    if (tiers.cache.length > 0) boxes.push({ label: '🔴 ' + tiers.cache[0].substring(0, 11), tier: 'cache' });

    // Database
    if (tiers.database.length > 0) boxes.push({ label: '💾 ' + tiers.database[0].substring(0, 11), tier: 'database' });

    // Build the horizontal flow
    if (boxes.length === 0) {
      return '  No architecture components found';
    }

    // Create 3 rows for boxes (top, middle, bottom)
    let row1 = '', row2 = '', row3 = '';

    boxes.forEach((box, i) => {
      const b = makeBox(box.label);
      const isLast = i === boxes.length - 1;

      row1 += b[0] + (isLast ? '' : '       ');
      row2 += b[1] + (isLast ? '' : arrow);
      row3 += b[2] + (isLast ? '' : '       ');
    });

    lines.push('');
    lines.push('  ' + row1);
    lines.push('  ' + row2);
    lines.push('  ' + row3);

    // Add storage/queue below if detailed
    if (detailed && (tiers.storage.length > 0 || tiers.queue.length > 0)) {
      lines.push('');
      let extras = [];
      if (tiers.storage.length > 0) extras.push('📦 Storage: ' + tiers.storage[0].substring(0, 20));
      if (tiers.queue.length > 0) extras.push('⚡ Queue: ' + tiers.queue[0].substring(0, 20));
      lines.push('  ' + extras.join('    '));
    }

    // Tech stack footer
    lines.push('');
    lines.push('  Tech: ' + techStack.slice(0, 10).join(' • '));
    lines.push('');

    return lines.join('\n');
  };

  const asciiDiagram = buildASCII();

  return (
    <div className="font-mono text-sm leading-relaxed bg-[var(--bg-elevated)] text-brand-400 p-4 rounded whitespace-pre border border-[var(--border)] overflow-x-auto">
      {asciiDiagram}
    </div>
  );
}

export default function SystemDesignPanel({ systemDesign, eraserDiagram, autoGenerateEraser = false, onGenerateEraserDiagram, question, cloudProvider = 'auto', qaHistory = [], onFollowUpQuestion, isProcessingFollowUp = false, diagramOnly = false }) {
  // Cloud-aware text translator. AWS service names embedded in the LLM
  // response (overview, architecture descriptions, API blurbs) get
  // swapped to the chosen cloud's equivalents at render time. This is a
  // safety net — the LLM should already be cloud-aware via prompts —
  // but it costs nothing and rescues older cached responses.
  const fmtCloud = useCloudFormatter();
  const [generatingEraser, setGeneratingEraser] = useState(false);
  const [diagramModal, setDiagramModal] = useState(false);
  const [proDiagramModal, setProDiagramModal] = useState(false);
  const [imageError, setImageError] = useState(false);

  const [generatingDiagram, setGeneratingDiagram] = useState(false);
  const [diagramCache, setDiagramCache] = useState({});
  const [diagramError, setDiagramError] = useState(null);
  const autoLoadedRef = useRef(null);
  const wheelTargetRef = useRef(null);
  // Detail + direction were user-toggleable in the legacy toolbar but are
  // now server-pinned to detailed/TB (PR #1 cutover). Kept as state so the
  // dependent code (diagramKey, handleGenerateDiagram retry, fullscreen
  // ASCII fallback) keeps reading values, just with no setter wired to
  // user input.
  // Default to overview + LR. detailed/TB produced 15-25 nodes stacked
  // vertically — far too dense for the design panel. Overview is 6-9
  // nodes in a 2-3 cluster left-to-right flow that fits the panel
  // without horizontal scroll and stays readable at fit-to-width zoom.
  const [diagramDetailLevel, setDiagramDetailLevel] = useState('overview');
  // direction is locked to TB on the server-side rendering pipeline,
  // but the local state still gets toggled when a user picks a cached
  // detail variant. Keep both reader + setter so handleGenerateDiagram
  // can reflect the active direction in cacheKey lookups without
  // throwing ReferenceError on the dropped setter.
  // LR (wide) reads better than TB (tall) in the side-by-side panel.
  const [diagramDirection, setDiagramDirection] = useState('LR');
  const [showASCII, setShowASCII] = useState(true);
  const [diagramScale, setDiagramScale] = useState(1);
  const [diagramTranslate, setDiagramTranslate] = useState({ x: 0, y: 0 });
  const [isDragging, setIsDragging] = useState(false);
  const [dragStart, setDragStart] = useState({ x: 0, y: 0 });
  const [diagramImgLoaded, setDiagramImgLoaded] = useState(false);

  const diagramKey = `${diagramDetailLevel}_${diagramDirection}`;
  const diagramData = diagramCache[diagramKey] || null;
  const hasComparison = systemDesign?.comparison || systemDesign?.comparisonDiagram;

  useEffect(() => {
    if (eraserDiagram?.imageUrl) {
      setImageError(false);
    }
  }, [eraserDiagram?.imageUrl]);

  // Locally-cached Eraser diagram from the cache-only lookup. We prefer
  // this over Graphviz when an Eraser row exists for the question because
  // Eraser produces cleaner architectures, but we never trigger a fresh
  // Eraser generation from auto-load (those calls cost Eraser API
  // credits). The "Auto Pro" pill remains the only way to spend on a
  // fresh Eraser render.
  const [cachedEraser, setCachedEraser] = useState(null);

  // Auto-load: try Eraser cache FIRST (free read), fall back to Graphviz
  // generation if the Eraser row doesn't exist. Eraser cache hits skip
  // the Graphviz call entirely, saving Anthropic credits and producing
  // a noticeably better diagram on warmed-up topics.
  useEffect(() => {
    if (!systemDesign?.included || !question) return;
    if (autoLoadedRef.current === question) return;
    autoLoadedRef.current = question;

    let cancelled = false;
    (async () => {
      // 1) Cache-only Eraser lookup (returns 404 if nothing cached).
      try {
        const headers = { 'Content-Type': 'application/json', ...getAuthHeaders() };
        const r = await fetch(`${API_URL}/api/diagram/eraser/lookup`, {
          method: 'POST',
          credentials: 'include',
          headers,
          body: JSON.stringify({ description: question, detailLevel: 'overview' }),
        });
        if (r.ok) {
          const data = await r.json();
          if (!cancelled && data?.imageUrl) {
            setCachedEraser({ imageUrl: data.imageUrl, editUrl: data.editUrl });
            return; // skip Graphviz generation — Eraser is the chosen render
          }
        }
      } catch {
        // network error — fall through to Graphviz
      }

      // 2) No Eraser cache → kick off Graphviz with current state defaults.
      if (cancelled) return;
      if (!diagramCache[diagramKey] && !generatingDiagram) {
        handleGenerateDiagram(diagramDetailLevel, diagramDirection);
      }
    })();

    return () => { cancelled = true; };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [systemDesign?.included, question]);

  // Attach wheel listener as NON-passive so e.preventDefault() works
  // for trackpad pinch-zoom on the diagram. React 18+ binds onWheel as
  // passive by default, which fires "Unable to preventDefault inside
  // passive event listener" warnings 49+ times per scroll. Manual
  // addEventListener with {passive: false} is the supported workaround.
  useEffect(() => {
    const el = wheelTargetRef.current;
    if (!el) return;
    const onWheel = (e) => {
      if (!diagramData) return;
      e.preventDefault();
      setDiagramScale((s) => Math.min(4, Math.max(0.3, s + (e.deltaY > 0 ? -0.1 : 0.1))));
    };
    el.addEventListener('wheel', onWheel, { passive: false });
    return () => el.removeEventListener('wheel', onWheel);
  }, [diagramData]);

  const handleGenerateEraser = async () => {
    if (!onGenerateEraserDiagram) return;
    setGeneratingEraser(true);
    try {
      await onGenerateEraserDiagram();
    } finally {
      setGeneratingEraser(false);
    }
  };

  const handleGenerateDiagram = async (detailLevel = 'overview', direction = 'LR') => {
    if (!question) return;

    const cacheKey = `${detailLevel}_${direction}`;
    if (diagramCache[cacheKey]) {
      setDiagramDetailLevel(detailLevel);
      setDiagramDirection(direction);
      return;
    }

    setDiagramDetailLevel(detailLevel);
    setDiagramDirection(direction);
    setDiagramScale(1);
    setDiagramTranslate({ x: 0, y: 0 });

    // 1. Pre-generated team diagrams take priority. apps/frontend/public/diagrams/
    //    has 80+ eraser-style PNGs hand-curated for common system-design problems.
    //    These are visually superior to anything the LLM produces, so we serve
    //    them directly when the question matches a known slug — no API call,
    //    no Anthropic spend, no LLM latency.
    const preGeneratedUrl = resolvePreGeneratedDiagram(question, cloudProvider || 'auto');
    if (preGeneratedUrl) {
      setDiagramError(null);
      setDiagramImgLoaded(false);
      setDiagramCache(prev => ({
        ...prev,
        [cacheKey]: {
          imageUrl: preGeneratedUrl,
          cloudProvider: cloudProvider || 'auto',
          detailLevel,
          direction,
          source: 'pre-generated',
        },
      }));
      return;
    }

    setGeneratingDiagram(true);
    setDiagramError(null);
    setDiagramImgLoaded(false);

    try {
      const response = await fetch(`${API_URL}/api/diagram/generate`, {
        credentials: 'include',
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...getAuthHeaders(),
        },
        body: JSON.stringify({
          question,
          cloudProvider: cloudProvider || 'auto',
          detailLevel,
          direction,
          cacheKey: question,
        }),
      });

      if (!response.ok) {
        let errorMessage = `Failed to generate diagram (${response.status})`;
        let needsSubscription = false;
        try {
          const errorData = await response.json();
          errorMessage = errorData.error || errorData.details || errorMessage;
          needsSubscription = errorData.subscriptionRequired || false;
        } catch {
          errorMessage = `Server error: ${response.status} ${response.statusText}`;
        }
        const err = new Error(errorMessage);
        err.subscriptionRequired = needsSubscription;
        throw err;
      }

      const result = await response.json();

      if (result.success && (result.image_url || result.mermaid_code)) {
        const entry = { cloudProvider: result.cloud_provider, detailLevel, direction };
        if (result.image_url) {
          entry.imageUrl = result.image_url.startsWith('http') ? result.image_url : `${API_URL}${result.image_url}`;
          entry.pythonCode = result.python_code;
        }
        if (result.mermaid_code) {
          entry.mermaidCode = result.mermaid_code;
        }
        setDiagramCache(prev => ({ ...prev, [cacheKey]: entry }));
      } else {
        throw new Error(result.error || 'Diagram generation failed');
      }
    } catch (error) {
      setDiagramError({ message: error.message, subscriptionRequired: error.subscriptionRequired || false });
    } finally {
      setGeneratingDiagram(false);
    }
  };

  if (!systemDesign || !systemDesign.included) {
    return (
      <div className="text-center py-8 text-[var(--text-muted)]">
        <p className="text-sm">System design analysis not available for this problem.</p>
        <p className="text-xs mt-1 text-[var(--text-muted)]">Try a different system design question or check your connection.</p>
      </div>
    );
  }

  // Calculate section counts for dynamic layout
  const hasRequirements = systemDesign.requirements && (systemDesign.requirements.functional?.length > 0 || systemDesign.requirements.nonFunctional?.length > 0);
  const hasArchitecture = systemDesign.architecture;
  const hasScalability = systemDesign.scalability?.length > 0;
  const hasTradeoffs = systemDesign.tradeoffs?.length > 0;
  const hasEdgeCases = systemDesign.edgeCases?.length > 0;
  const hasTechJustifications = systemDesign.techJustifications?.length > 0;
  const hasApiDesign = systemDesign.apiDesign?.length > 0;
  const hasDataModel = systemDesign.dataModel?.length > 0;
  const hasDiagram = !!systemDesign.diagram;
  const showProDiagram = autoGenerateEraser || eraserDiagram;

  // Diagram-only mode: render just the cloud architecture diagram with controls
  //
  // The Overview/Detailed and LR/TB toggles were removed in lockstep with
  // PR #1 — direction is server-pinned to TB and detail to detailed, so
  // those buttons would've sent a body that the backend ignores. The
  // CloudProviderSelector at the top now controls AWS/Azure/GCP; everything
  // else is auto.
  if (diagramOnly) {
    return (
      <div className="h-full flex flex-col overflow-hidden" style={{ background: 'var(--bg-app)' }}>
        {/* Toolbar — same grammar as Lumora design Input Tab Header
            (DesignLayout.tsx:695): cam-hero-strip background, gold-leaf
            bottom border, sharp pill toggles. */}
        <div
          className="flex items-center justify-between px-3 py-2 flex-shrink-0"
          style={{
            background: 'var(--cam-hero-strip)',
            borderBottom: '2px solid var(--cam-gold-leaf)',
          }}
        >
          <div className="flex items-center gap-2 min-w-0">
            <span className="text-[11px] font-bold uppercase tracking-[0.12em] text-white whitespace-nowrap">
              Cloud Architecture
            </span>
            {diagramData?.cloudProvider && (
              <span
                className="text-[10px] font-bold uppercase tracking-wider px-2 py-0.5"
                style={{
                  background: 'rgba(255,255,255,0.08)',
                  border: '1px solid rgba(255,255,255,0.16)',
                  borderRadius: 999,
                  color: 'rgba(255,255,255,0.85)',
                }}
              >
                {diagramData.cloudProvider}
              </span>
            )}
          </div>
          {diagramData && (
            <div
              className="flex items-center gap-1 px-1 py-1"
              style={{
                background: 'rgba(255,255,255,0.06)',
                border: '1px solid rgba(255,255,255,0.16)',
                borderRadius: 999,
                boxShadow: 'inset 0 1px 0 rgba(255,255,255,0.06), 0 1px 2px rgba(0,0,0,0.25)',
              }}
            >
              <button
                onClick={() => setDiagramScale(s => Math.max(0.3, s - 0.15))}
                className="w-6 h-6 flex items-center justify-center text-xs font-bold"
                style={{ color: 'rgba(255,255,255,0.85)', borderRadius: 999 }}
                title="Zoom out"
              >−</button>
              <span className="text-[10px] font-mono w-9 text-center tabular-nums" style={{ color: 'rgba(255,255,255,0.7)' }}>
                {Math.round(diagramScale * 100)}%
              </span>
              <button
                onClick={() => setDiagramScale(s => Math.min(4, s + 0.15))}
                className="w-6 h-6 flex items-center justify-center text-xs font-bold"
                style={{ color: 'rgba(255,255,255,0.85)', borderRadius: 999 }}
                title="Zoom in"
              >+</button>
              <button
                onClick={() => { setDiagramScale(1); setDiagramTranslate({ x: 0, y: 0 }); }}
                className="px-3 h-6 text-[10px] font-bold uppercase tracking-wider"
                style={{ background: 'var(--cam-gold-leaf)', color: '#020617', borderRadius: 999, boxShadow: '0 1px 2px rgba(0,0,0,0.2)' }}
                title="Reset to fit"
              >Fit</button>
              <button
                onClick={() => setDiagramModal(true)}
                className="w-6 h-6 flex items-center justify-center"
                style={{ color: 'rgba(255,255,255,0.85)', borderRadius: 999 }}
                title="Full screen"
              >
                <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 8V4m0 0h4M4 4l5 5m11-1V4m0 0h-4m4 0l-5 5M4 16v4m0 0h4m-4 0l5-5m11 5l-5-5m5 5v-4m0 4h-4" /></svg>
              </button>
            </div>
          )}
        </div>
        {/* Diagram with Pan+Zoom — fixed viewport-relative max-height so the
            container itself never grows beyond the visible pane. The image
            inside fits-to-container at scale=1 (object-contain), then the
            user can zoom/pan from there. The previous implementation rendered
            the image at native pixel size (maxWidth:'none') which produced
            multi-page scrolls for tall TB diagrams. */}
        <div
          ref={wheelTargetRef}
          className="flex-1 min-h-0 overflow-hidden cursor-grab active:cursor-grabbing relative flex items-center justify-center"
          style={{ background: 'var(--bg-app)', maxHeight: 'calc(100vh - 220px)' }}
          onMouseDown={(e) => { if (diagramData) { setIsDragging(true); setDragStart({ x: e.clientX - diagramTranslate.x, y: e.clientY - diagramTranslate.y }); } }}
          onMouseMove={(e) => { if (isDragging) { setDiagramTranslate({ x: e.clientX - dragStart.x, y: e.clientY - dragStart.y }); } }}
          onMouseUp={() => setIsDragging(false)}
          onMouseLeave={() => setIsDragging(false)}
        >
          {diagramData && !diagramError ? (
            diagramData.imageUrl ? (
              <>
                {!diagramImgLoaded && (
                  <div className="absolute inset-0 flex flex-col items-center justify-center text-[var(--text-muted)]">
                    <svg className="w-6 h-6 animate-spin text-[var(--accent)] mb-2" fill="none" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" /><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" /></svg>
                    <span className="text-xs">Loading diagram...</span>
                  </div>
                )}
                <img
                  src={diagramData.imageUrl}
                  alt="Cloud Architecture"
                  className="select-none"
                  draggable={false}
                  style={{
                    // Fit-to-container at scale=1, then user-zoom multiplies
                    // from there. transformOrigin center keeps zoom anchored
                    // on the visible center instead of the top-left corner.
                    transform: `translate(${diagramTranslate.x}px, ${diagramTranslate.y}px) scale(${diagramScale})`,
                    transformOrigin: 'center center',
                    maxWidth: '100%',
                    maxHeight: '100%',
                    objectFit: 'contain',
                    display: diagramImgLoaded ? 'block' : 'none',
                  }}
                  onLoad={() => setDiagramImgLoaded(true)}
                  onError={() => { setDiagramImgLoaded(false); setDiagramError({ message: 'Image failed to load. Click Retry to regenerate.', subscriptionRequired: false }); }}
                />
              </>
            ) : diagramData.mermaidCode ? (
              <div className="p-2 bg-[var(--bg-surface)] rounded" style={{ transform: `scale(${diagramScale})`, transformOrigin: 'center center' }}>
                <MermaidDiagram content={diagramData.mermaidCode} />
              </div>
            ) : null
          ) : generatingDiagram ? (
            <div className="flex flex-col items-center justify-center h-full text-[var(--text-muted)]">
              <svg className="w-6 h-6 animate-spin text-[var(--accent)] mb-2" fill="none" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" /><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" /></svg>
              <span className="text-xs">Generating diagram...</span>
            </div>
          ) : diagramError ? (
            <div className="flex flex-col items-center justify-center h-full p-6">
              {diagramError.subscriptionRequired ? (
                <>
                  <div className="w-12 h-12 rounded-2xl bg-amber-500/10 flex items-center justify-center mb-3">
                    <svg className="w-6 h-6 text-amber-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" /></svg>
                  </div>
                  <p className="text-sm font-semibold text-[var(--text-primary)] mb-1">Free diagrams used up</p>
                  <p className="text-xs text-[var(--text-muted)] mb-4 text-center max-w-xs">Upgrade to Premium for unlimited architecture diagram generation.</p>
                  <Link to="/pricing" className="px-4 py-2 bg-[var(--accent)] text-white text-xs font-bold rounded-lg hover:bg-[var(--accent-hover)] transition-colors">View Plans</Link>
                </>
              ) : (
                <>
                  <div className="w-12 h-12 rounded-2xl bg-red-500/10 flex items-center justify-center mb-3">
                    <svg className="w-6 h-6 text-red-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z" /></svg>
                  </div>
                  <p className="text-sm font-semibold text-[var(--text-primary)] mb-1">Diagram generation failed</p>
                  <p className="text-xs text-[var(--text-muted)] mb-3 text-center max-w-xs">{diagramError.message}</p>
                  <button onClick={() => { setDiagramError(null); handleGenerateDiagram(diagramDetailLevel, diagramDirection); }} className="px-4 py-2 bg-[var(--bg-elevated)] text-[var(--text-secondary)] text-xs font-bold rounded-lg hover:bg-[var(--bg-elevated)] transition-colors">Retry</button>
                </>
              )}
            </div>
          ) : (
            <div className="flex flex-col items-center justify-center h-full text-[var(--text-muted)]">
              <svg className="w-8 h-8 mb-2" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M3 15a4 4 0 004 4h9a5 5 0 10-.1-9.999 5.002 5.002 0 10-9.78 2.096A4.001 4.001 0 003 15z" /></svg>
              <p className="text-xs">Auto-generating diagram...</p>
            </div>
          )}
        </div>
        <DiagramModal isOpen={diagramModal} onClose={() => setDiagramModal(false)} title={`Architecture Diagram${diagramData?.cloudProvider ? ` (${diagramData.cloudProvider.toUpperCase()})` : ''}`}>
          {diagramData && <div className="max-w-full max-h-full">{diagramData.imageUrl ? <img src={diagramData.imageUrl} alt="Cloud Architecture" className="max-w-full max-h-[80vh] object-contain" /> : diagramData.mermaidCode ? <MermaidDiagram content={diagramData.mermaidCode} /> : null}</div>}
        </DiagramModal>
      </div>
    );
  }

  return (
    <div className="rounded-lg animate-fade-in bg-[var(--bg-surface)] border border-[var(--border)] h-full flex flex-col overflow-hidden">
      {/* Header — same navy-strip + gold-leaf chrome as every section
          card below, so the panel reads as a single design vocabulary. */}
      <div
        className="flex-shrink-0 flex items-center justify-between px-3 py-2"
        style={{
          background: 'var(--cam-hero-strip)',
          borderBottom: '2px solid var(--cam-gold-leaf)',
        }}
      >
        <span className="text-[11px] font-bold uppercase tracking-[0.12em] text-white">System Design</span>
        {/* Cloud-platform selector — same instance as the docs header,
            backed by useCloudProvider so a flip here propagates to every
            other diagram surface in the same browser. */}
        <CloudProviderSelector variant="compact" />
      </div>

      <div className="flex-1 overflow-y-auto overflow-x-hidden min-h-0 p-3">
        {/* Focused Answer Mode - For SLI/SLO/concept questions */}
        {systemDesign.focusedAnswer && systemDesign.categories && (
          <div className="space-y-2">
            {/* Overview for focused answer */}
            {systemDesign.overview && (
              <div className="rounded p-2 bg-[var(--bg-elevated)]/30 border border-[var(--border)]">
                <p className="text-xs text-[var(--text-primary)] leading-snug">{fmtCloud(systemDesign.overview)}</p>
              </div>
            )}

            {/* Categories as Compact Tables */}
            <div className="grid grid-cols-1 xl:grid-cols-2 gap-2">
              {systemDesign.categories.map((category, catIdx) => (
                <div key={catIdx} className="rounded overflow-hidden border border-[var(--border)]">
                  <div className="bg-brand-400/10 px-2 py-1 border-b border-[var(--border)]">
                    <h4 className="text-xs font-semibold text-brand-400">{category.name}</h4>
                  </div>
                  <div className="bg-[var(--bg-elevated)] overflow-x-auto">
                    <table className="w-full text-xs">
                      <thead>
                        <tr className="border-b border-[var(--border)]">
                          <th className="text-left px-2 py-1 text-[var(--text-secondary)] font-semibold ">Metric</th>
                          <th className="text-left px-2 py-1 text-[var(--text-secondary)] font-semibold ">Target</th>
                          <th className="text-left px-2 py-1 text-[var(--text-secondary)] font-semibold ">Measurement</th>
                          <th className="text-left px-2 py-1 text-[var(--text-secondary)] font-semibold ">Alert</th>
                        </tr>
                      </thead>
                      <tbody>
                        {category.items?.map((item, itemIdx) => (
                          <tr key={itemIdx} className="border-b border-[var(--border)]/30 last:border-b-0">
                            <td className="px-2 py-1 text-[var(--text-primary)] font-medium">{item.metric || item.name || '-'}</td>
                            <td className="px-2 py-1 text-brand-400 font-mono text-xs">{item.target || item.value || '-'}</td>
                            <td className="px-2 py-1 text-[var(--text-primary)]">{item.measurement || item.description || '-'}</td>
                            <td className="px-2 py-1 text-warning-400 text-xs">{item.alertThreshold || item.alert || '-'}</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Full System Design Mode - Optimized Grid Layout */}
        {!systemDesign.focusedAnswer && (
          <div className="grid grid-cols-1 sm:grid-cols-12 gap-4 auto-rows-min">

            {/* Row 1: Explanation */}
            {systemDesign.overview && (
              <SectionCard title="Overview" className="col-span-full" accent="var(--cam-gold-leaf)">
                <p className="text-sm text-[var(--text-secondary)] leading-relaxed">{fmtCloud(systemDesign.overview)}</p>
              </SectionCard>
            )}
            {hasScalability && (
              <SectionCard title="Scalability" className="col-span-full" accent="var(--cam-gold-leaf)">
                <div className="flex flex-wrap gap-1.5">
                  {systemDesign.scalability.map((item, i) => (
                    <span key={i} className="inline-flex items-center gap-1.5 px-2.5 py-1 text-xs font-medium rounded-md bg-[var(--bg-elevated)] text-[var(--text-primary)] border border-[var(--border)]" title={item}>
                      <span className="w-1.5 h-1.5 rounded-full bg-[var(--accent)] flex-shrink-0" />
                      {item}
                    </span>
                  ))}
                </div>
              </SectionCard>
            )}

            {/* Row 2: Requirements + Tradeoffs + Edge Cases (4 columns) */}
            {(hasRequirements || hasTradeoffs || hasEdgeCases) && (
              <>
                {systemDesign.requirements?.functional?.length > 0 && (
                  <SectionCard title="Functional" className="col-span-full sm:col-span-3" accent="var(--cam-gold-leaf)">
                    <ul className="space-y-1.5">
                      {systemDesign.requirements.functional.map((req, i) => (
                        <li key={i} className="text-sm text-[var(--text-secondary)] leading-snug flex items-start gap-2">
                          <span className="text-[var(--accent)] mt-1.5 flex-shrink-0 w-1 h-1 rounded-full bg-current" />
                          <span>{req}</span>
                        </li>
                      ))}
                    </ul>
                  </SectionCard>
                )}
                {systemDesign.requirements?.nonFunctional?.length > 0 && (
                  <SectionCard title="Non-Functional" className="col-span-full sm:col-span-3" accent="var(--cam-gold-leaf)">
                    <ul className="space-y-1.5">
                      {systemDesign.requirements.nonFunctional.map((req, i) => (
                        <li key={i} className="text-sm text-[var(--text-secondary)] leading-snug flex items-start gap-2">
                          <span className="text-[var(--accent)] mt-1.5 flex-shrink-0 w-1 h-1 rounded-full bg-current" />
                          <span>{req}</span>
                        </li>
                      ))}
                    </ul>
                  </SectionCard>
                )}
                {hasTradeoffs && (
                  <SectionCard title="Tradeoffs" className="col-span-full sm:col-span-3" accent="var(--cam-gold-leaf)">
                    <ul className="space-y-1.5">
                      {systemDesign.tradeoffs.slice(0, 5).map((tradeoff, i) => (
                        <li key={i} className="text-sm text-[var(--text-secondary)] leading-snug flex items-start gap-2">
                          <span className="text-amber-500 mt-1.5 flex-shrink-0 w-1 h-1 rounded-full bg-current" />
                          <span>{typeof tradeoff === 'string' ? tradeoff.replace(/^Tradeoff \d+:\s*/i, '') : tradeoff}</span>
                        </li>
                      ))}
                    </ul>
                  </SectionCard>
                )}
                {hasEdgeCases && (
                  <SectionCard title="Edge Cases" className="col-span-full sm:col-span-3" accent="var(--cam-gold-leaf)">
                    <ul className="space-y-1.5">
                      {systemDesign.edgeCases.slice(0, 5).map((edge, i) => (
                        <li key={i} className="text-sm text-[var(--text-secondary)] leading-snug flex items-start gap-2">
                          <span className="text-rose-500 mt-1.5 flex-shrink-0 w-1 h-1 rounded-full bg-current" />
                          <span>{typeof edge === 'string' ? edge.replace(/^Edge case \d+:\s*/i, '') : edge}</span>
                        </li>
                      ))}
                    </ul>
                  </SectionCard>
                )}
              </>
            )}

            {/* Row 3: Architecture Components */}
            {hasArchitecture && (
              <SectionCard title="Architecture Components" className="col-span-full" accent="var(--cam-gold-leaf)">
                <div className="flex flex-wrap gap-1 mb-2">
                  {systemDesign.architecture.components?.map((component, i) => (
                    <span key={i} className="px-1.5 py-0.5 bg-[var(--bg-elevated)] text-[var(--text-primary)] text-xs rounded border border-[var(--border)]">
                      {component}
                    </span>
                  ))}
                </div>
                {systemDesign.architecture.description && (
                  <p className="text-xs text-[var(--text-secondary)] leading-snug">{fmtCloud(systemDesign.architecture.description)}</p>
                )}
              </SectionCard>
            )}


            {/* Row 3b: API Design */}
            {hasApiDesign && (
              <SectionCard title="API Design" count={systemDesign.apiDesign.length} className="col-span-full" accent="var(--cam-gold-leaf)">
                <div className="space-y-1.5">
                  {systemDesign.apiDesign.map((api, i) => (
                    <div key={i} className="bg-[var(--bg-elevated)] border border-[var(--border)] rounded p-2">
                      <div className="flex items-center gap-2 mb-1">
                        <span className={`px-1.5 py-0.5 text-xs font-bold rounded ${
                          api.method === 'GET' ? 'bg-blue-100 text-blue-700' :
                          api.method === 'POST' ? 'bg-[var(--success)]/10 text-[var(--success)]' :
                          api.method === 'PUT' ? 'bg-yellow-100 text-yellow-700' :
                          api.method === 'DELETE' ? 'bg-red-100 text-red-700' :
                          'bg-[var(--bg-elevated)] text-[var(--text-secondary)]'
                        }`}>{api.method}</span>
                        <code className="text-xs font-mono text-[var(--text-primary)]">{api.endpoint}</code>
                      </div>
                      <p className="text-xs text-[var(--text-secondary)] leading-snug">{fmtCloud(api.description)}</p>
                      {(api.request || api.response) && (
                        <div className="grid grid-cols-2 gap-2 mt-1.5">
                          {api.request && (
                            <div>
                              <span className="text-xs font-semibold text-[var(--text-muted)] uppercase">Request</span>
                              <pre className="text-xs text-[var(--text-secondary)] bg-[var(--bg-elevated)] rounded p-1.5 mt-0.5 overflow-x-auto font-mono whitespace-pre-wrap">{typeof api.request === 'string' ? api.request : JSON.stringify(api.request, null, 2)}</pre>
                            </div>
                          )}
                          {api.response && (
                            <div>
                              <span className="text-xs font-semibold text-[var(--text-muted)] uppercase">Response</span>
                              <pre className="text-xs text-[var(--text-secondary)] bg-[var(--bg-elevated)] rounded p-1.5 mt-0.5 overflow-x-auto font-mono whitespace-pre-wrap">{typeof api.response === 'string' ? api.response : JSON.stringify(api.response, null, 2)}</pre>
                            </div>
                          )}
                        </div>
                      )}
                    </div>
                  ))}
                </div>
              </SectionCard>
            )}

            {/* Row 3c: Data Model */}
            {hasDataModel && (
              <SectionCard title="Data Model" count={systemDesign.dataModel.length} className="col-span-full" accent="var(--cam-gold-leaf)">
                <div className="grid grid-cols-1 lg:grid-cols-2 gap-1.5 items-start">
                  {systemDesign.dataModel.map((model, i) => (
                    <div key={i} className="bg-[var(--bg-elevated)] border border-[var(--border)] rounded overflow-hidden">
                      <div className="bg-[var(--bg-elevated)] px-2 py-1 border-b border-[var(--border)]">
                        <span className="text-xs font-bold text-[var(--text-primary)] font-mono">{model.table}</span>
                      </div>
                      <div className="px-2 py-1">
                        <table className="w-full text-xs">
                          <thead>
                            <tr className="border-b border-[var(--border)]">
                              <th className="text-left py-0.5 text-[var(--text-muted)] font-semibold">Field</th>
                              <th className="text-left py-0.5 text-[var(--text-muted)] font-semibold">Type</th>
                              <th className="text-left py-0.5 text-[var(--text-muted)] font-semibold">Description</th>
                            </tr>
                          </thead>
                          <tbody>
                            {model.fields?.map((field, fi) => (
                              <tr key={fi} className="border-b border-[var(--border)] last:border-0">
                                <td className="py-0.5 font-mono text-[var(--text-primary)]">{field.name}</td>
                                <td className="py-0.5 text-blue-600 font-mono">{field.type}</td>
                                <td className="py-0.5 text-[var(--text-secondary)]">{fmtCloud(field.description)}</td>
                              </tr>
                            ))}
                          </tbody>
                        </table>
                      </div>
                    </div>
                  ))}
                </div>
              </SectionCard>
            )}

            {/* Row 3d: System Flow Diagram — REMOVED.
                Was rendering MermaidDiagram from `systemDesign.diagram`,
                which violated the project's no-Mermaid rule and stuck on
                "Rendering diagram…" in production. The page already has
                two authoritative diagram views: Cloud Architecture (Python
                Graphviz PNG, served from cache) on the structural side,
                and the Architecture Flow ASCII below this row for a
                text-based traversal. A third Mermaid view added confusion
                without new information. */}

            {/* Row 4: ASCII Diagram - Full Width.
                Guarded: only render once the systemDesign has REAL
                architecture content. Without this, the panel renders
                a "Client" + empty "Tech:" stub during streaming —
                appearing FIRST while every other section is still
                empty, which made Architecture Flow look like the
                main / loaded section before anything else arrived. */}
            {(hasArchitecture || hasTechJustifications) && (
              <SectionCard
                title="Architecture Flow"
                className="col-span-full"
                accent="var(--cam-gold-leaf)"
                actions={
                  <button
                    onClick={() => setDiagramDetailLevel(diagramDetailLevel === 'detailed' ? 'overview' : 'detailed')}
                    className="px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider rounded-full"
                    style={{
                      background: 'var(--cam-gold-leaf)',
                      color: '#020617',
                      boxShadow: '0 1px 2px rgba(0,0,0,0.2)',
                    }}
                  >
                    {diagramDetailLevel === 'detailed' ? 'Detailed' : 'Overview'}
                  </button>
                }
              >
                <ASCIIDiagram systemDesign={systemDesign} detailed={diagramDetailLevel === 'detailed'} />
              </SectionCard>
            )}

            {/* Row 5: Tech Justifications (compact grid) */}
            {hasTechJustifications && (
              <SectionCard title="Technologies" count={systemDesign.techJustifications.length} className="col-span-full" accent="var(--cam-gold-leaf)">
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-3">
                  {systemDesign.techJustifications.map((item, i) => (
                    <div key={i} className="rounded-lg p-3 bg-[var(--bg-elevated)] border border-[var(--border)] hover:border-[var(--accent)] transition-colors">
                      <div className="flex flex-wrap items-center gap-1.5 mb-2">
                        <span className="px-2 py-0.5 bg-[var(--accent)] text-white text-xs font-semibold rounded-md">{item.tech}</span>
                        {item.category && <span className="px-2 py-0.5 bg-[var(--bg-surface)] text-[var(--text-secondary)] text-xs font-medium rounded-md border border-[var(--border)]">{item.category}</span>}
                      </div>
                      <p className="text-sm text-[var(--text-primary)] leading-snug line-clamp-3">{item.why}</p>
                      {item.alternatives && <p className="text-xs text-[var(--text-muted)] mt-1.5 truncate"><span className="font-semibold text-[var(--text-secondary)]">Alt:</span> {item.alternatives}</p>}
                    </div>
                  ))}
                </div>
              </SectionCard>
            )}

            {/* Row 6: Comparison (side by side) */}
            {systemDesign.comparison && (
              <div className="col-span-full grid grid-cols-1 md:grid-cols-2 gap-3">
                {systemDesign.comparison.approach1 && (
                  <SectionCard
                    title={systemDesign.comparison.approach1.name || 'Approach 1'}
                    bodyClassName="p-3"
                    accent="var(--cam-gold-leaf)"
                  >
                    <div className="grid grid-cols-2 gap-2">
                      {systemDesign.comparison.approach1.pros?.length > 0 && (
                        <div>
                          <span className="text-xs font-semibold text-brand-400 uppercase">Pros</span>
                          <ul className="mt-0.5 space-y-0.5">
                            {systemDesign.comparison.approach1.pros.slice(0, 3).map((pro, i) => (
                              <li key={i} className="text-xs text-[var(--text-primary)] flex items-start gap-1">
                                <span className="text-brand-400 mt-0.5 text-xs">+</span>
                                <span className="line-clamp-1">{pro}</span>
                              </li>
                            ))}
                          </ul>
                        </div>
                      )}
                      {systemDesign.comparison.approach1.cons?.length > 0 && (
                        <div>
                          <span className="text-xs font-semibold text-error-400 uppercase">Cons</span>
                          <ul className="mt-0.5 space-y-0.5">
                            {systemDesign.comparison.approach1.cons.slice(0, 3).map((con, i) => (
                              <li key={i} className="text-xs text-[var(--text-primary)] flex items-start gap-1">
                                <span className="text-error-400 mt-0.5 text-xs">-</span>
                                <span className="line-clamp-1">{con}</span>
                              </li>
                            ))}
                          </ul>
                        </div>
                      )}
                    </div>
                  </SectionCard>
                )}
                {systemDesign.comparison.approach2 && (
                  <SectionCard
                    title={systemDesign.comparison.approach2.name || 'Approach 2'}
                    bodyClassName="p-3"
                    accent="var(--cam-gold-leaf)"
                  >
                    <div className="grid grid-cols-2 gap-2">
                      {systemDesign.comparison.approach2.pros?.length > 0 && (
                        <div>
                          <span className="text-xs font-semibold text-brand-400 uppercase">Pros</span>
                          <ul className="mt-0.5 space-y-0.5">
                            {systemDesign.comparison.approach2.pros.slice(0, 3).map((pro, i) => (
                              <li key={i} className="text-xs text-[var(--text-primary)] flex items-start gap-1">
                                <span className="text-brand-400 mt-0.5 text-xs">+</span>
                                <span className="line-clamp-1">{pro}</span>
                              </li>
                            ))}
                          </ul>
                        </div>
                      )}
                      {systemDesign.comparison.approach2.cons?.length > 0 && (
                        <div>
                          <span className="text-xs font-semibold text-error-400 uppercase">Cons</span>
                          <ul className="mt-0.5 space-y-0.5">
                            {systemDesign.comparison.approach2.cons.slice(0, 3).map((con, i) => (
                              <li key={i} className="text-xs text-[var(--text-primary)] flex items-start gap-1">
                                <span className="text-error-400 mt-0.5 text-xs">-</span>
                                <span className="line-clamp-1">{con}</span>
                              </li>
                            ))}
                          </ul>
                        </div>
                      )}
                    </div>
                  </SectionCard>
                )}
              </div>
            )}

            {/* Row 7: Follow-up Questions — canonical questions an
                interviewer would ask after this design. */}
            {Array.isArray(systemDesign.followUpQuestions) && systemDesign.followUpQuestions.length > 0 && (
              <SectionCard
                title="Follow-up Questions"
                count={systemDesign.followUpQuestions.length}
                className="col-span-full"
                accent="var(--cam-gold-leaf)"
              >
                <ol className="space-y-2.5">
                  {systemDesign.followUpQuestions.map((q, i) => (
                    <li key={i} className="rounded-lg p-3 bg-[var(--bg-elevated)] border border-[var(--border)] flex items-start gap-3">
                      <span className="w-6 h-6 rounded-md flex-shrink-0 flex items-center justify-center text-xs font-semibold bg-[var(--accent)] text-white">{i + 1}</span>
                      <p className="text-sm text-[var(--text-primary)] leading-relaxed pt-0.5">
                        {typeof q === 'string' ? q : (q.question || q.q || '')}
                      </p>
                    </li>
                  ))}
                </ol>
              </SectionCard>
            )}
          </div>
        )}

        {/* Cloud Architecture Diagram Modal */}
        <DiagramModal
          isOpen={diagramModal}
          onClose={() => setDiagramModal(false)}
          title={`Architecture Diagram${diagramData?.cloudProvider ? ` (${diagramData.cloudProvider.toUpperCase()})` : ''}`}
        >
          {diagramData && (
            <div className="max-w-full max-h-full">
              {diagramData.imageUrl ? (
                <CloudArchitectureDiagram
                  imageUrl={diagramData.imageUrl}
                  expanded={true}
                  cloudProvider={diagramData.cloudProvider}
                />
              ) : diagramData.mermaidCode ? (
                <MermaidDiagram content={diagramData.mermaidCode} />
              ) : null}
            </div>
          )}
        </DiagramModal>

        {/* Pro Diagram Modal (Eraser.io) */}
        <DiagramModal
          isOpen={proDiagramModal}
          onClose={() => setProDiagramModal(false)}
          title="Pro Diagram"
        >
          {eraserDiagram && (
            <div className="max-w-full max-h-full">
              <img
                src={eraserDiagram.imageUrl}
                alt="Architecture Diagram"
                className="max-w-full max-h-[80vh] object-contain"
              />
              {eraserDiagram.editUrl && (
                <div className="mt-4 text-center">
                  <a
                    href={eraserDiagram.editUrl}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="inline-flex items-center gap-2 px-4 py-2 text-sm font-medium rounded-lg bg-[var(--bg-elevated)] text-[var(--text-primary)] border border-[var(--border)] hover:bg-[var(--bg-elevated)] transition-colors"
                  >
                    <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" />
                    </svg>
                    Edit on Eraser.io
                  </a>
                </div>
              )}
            </div>
          )}
        </DiagramModal>
      </div>
    </div>
  );
}
