/* AUTO-GENERATED by apps/camora/scripts/research-topic.py --phase=generate.
   Do not edit by hand. Re-run the script to regenerate. */

type DiagramEntry = { id: string; title: string; file: string };
type TopicDiagrams = { deepDives: DiagramEntry[]; tradeoffs: DiagramEntry[] };

export const GENERATED_DIAGRAMS: Record<string, TopicDiagrams> = {};
