/* AUTO-GENERATED by apps/camora/scripts/research-topic.py --phase=generate.
   Do not edit by hand. Re-run the script to regenerate. */

type DiagramEntry = { id: string; title: string; file: string };
type TopicDiagrams = { deepDives: DiagramEntry[]; tradeoffs: DiagramEntry[] };

export const GENERATED_DIAGRAMS: Record<string, TopicDiagrams> = {
  'instagram': {
    deepDives: [
    {
        "id": "notification-system",
        "title": "Real-Time Notification System",
        "file": "deep-dive-notification-system.png"
    },
    {
        "id": "counter-service",
        "title": "Like & Follower Counter Service",
        "file": "deep-dive-counter-service.png"
    },
    {
        "id": "search-indexing",
        "title": "Search & Hashtag Indexing Pipeline",
        "file": "deep-dive-search-indexing.png"
    }
],
    tradeoffs: [
    {
        "id": "feed-delivery",
        "title": "Push vs Pull vs Hybrid Feed",
        "file": "tradeoff-feed-delivery.png"
    },
    {
        "id": "metadata-store",
        "title": "SQL vs NoSQL for Post Metadata",
        "file": "tradeoff-metadata-store.png"
    },
    {
        "id": "image-storage-cdn",
        "title": "Pre-generate vs On-the-Fly Image Variants",
        "file": "tradeoff-image-storage-cdn.png"
    }
],
  },
};
