/* AUTO-GENERATED by apps/camora/scripts/research-topic.py --phase=generate.
   Do not edit by hand. Re-run the script to regenerate. */

type DiagramEntry = { id: string; title: string; file: string };
type TopicDiagrams = { deepDives: DiagramEntry[]; tradeoffs: DiagramEntry[] };

export const GENERATED_DIAGRAMS: Record<string, TopicDiagrams> = {
  'url-shortener': {
    deepDives: [
    {
        "id": "short-code-generation",
        "title": "Short Code Generation & Collision Handling",
        "file": "deep-dive-short-code-generation.png"
    },
    {
        "id": "read-path-caching",
        "title": "Read Path with Multi-Layer Cache",
        "file": "deep-dive-read-path-caching.png"
    },
    {
        "id": "analytics-pipeline",
        "title": "Click Analytics Pipeline",
        "file": "deep-dive-analytics-pipeline.png"
    }
],
    tradeoffs: [
    {
        "id": "code-generation-strategy",
        "title": "Hash-based vs Counter-based vs Random Code Generation",
        "file": "tradeoff-code-generation-strategy.png"
    },
    {
        "id": "database-choice",
        "title": "SQL vs NoSQL for URL Mappings",
        "file": "tradeoff-database-choice.png"
    },
    {
        "id": "analytics-processing",
        "title": "Real-time Stream vs Batch Analytics",
        "file": "tradeoff-analytics-processing.png"
    }
],
  },
};
