import { Link } from 'react-router-dom';
import DocsPageLayout from './_layout';
import DocsCallout from '../../components/shared/docs/DocsCallout';

export default function PracticeDocsPage() {
  return (
    <DocsPageLayout
      title="Capra Practice"
      description="DSA problems, Blind 75, system design exercises, and behavioral STAR drills."
      path="/docs/practice"
      eyebrow="USER GUIDE"
      breadcrumbs={[{ label: 'Capra Practice' }]}
      onThisPage={[
        { id: 'overview', label: 'Overview' },
        { id: 'dsa-problems', label: 'DSA problems' },
        { id: 'blind-75', label: 'Blind 75', depth: 1 },
        { id: 'system-design', label: 'System design' },
        { id: 'behavioral', label: 'Behavioral STAR' },
        { id: 'how-grading-works', label: 'How grading works' },
      ]}
    >
      <section id="overview" className="mb-10 scroll-mt-24">
        <h2 className="text-2xl font-bold mb-3">Overview</h2>
        <p className="text-[15px] leading-relaxed mb-3" style={{ color: 'var(--text-secondary)' }}>
          Practice complements <Link to="/docs/prepare" className="text-[var(--accent)] underline">Prepare</Link> — instead of reading topics, you solve problems.
          Open <Link to="/capra/practice" className="text-[var(--accent)] underline">Capra Practice</Link> from the main nav.
        </p>
      </section>

      <section id="dsa-problems" className="mb-10 scroll-mt-24">
        <h2 className="text-2xl font-bold mb-3">DSA problems</h2>
        <p className="text-[15px] leading-relaxed mb-3" style={{ color: 'var(--text-secondary)' }}>
          200+ algorithm problems covering the standard interview taxonomy: arrays, strings, hash maps,
          two pointers, sliding window, binary search, trees, graphs, dynamic programming, backtracking, and
          greedy. Each problem includes a difficulty rating, expected complexity, and worked solution with
          three alternative approaches when relevant.
        </p>
        <h3 id="blind-75" className="text-xl font-bold mt-6 mb-3 scroll-mt-24">Blind 75</h3>
        <p className="text-[15px] leading-relaxed" style={{ color: 'var(--text-secondary)' }}>
          The canonical Blind 75 list is curated as a guided track — open
          <Link to="/capra/blind75" className="text-[var(--accent)] underline ml-1">Capra Blind 75</Link>. Topics are ordered by category
          and difficulty so you build pattern recognition, not just solve random problems.
        </p>
      </section>

      <section id="system-design" className="mb-10 scroll-mt-24">
        <h2 className="text-2xl font-bold mb-3">System design</h2>
        <p className="text-[15px] leading-relaxed" style={{ color: 'var(--text-secondary)' }}>
          50+ system design exercises with a guided rubric: clarify requirements, estimate scale, draw the
          high-level architecture, deep-dive on the trickiest component, discuss trade-offs. Each problem
          includes architecture diagrams generated by the Python `diagrams` library.
        </p>
      </section>

      <section id="behavioral" className="mb-10 scroll-mt-24">
        <h2 className="text-2xl font-bold mb-3">Behavioral STAR</h2>
        <p className="text-[15px] leading-relaxed mb-3" style={{ color: 'var(--text-secondary)' }}>
          Behavioral practice is structured around STAR (Situation / Task / Action / Result) and Amazon's
          leadership principles. The practice surface gives you a prompt; you write a story; AI feedback
          scores it on rubric clarity and coaches improvements.
        </p>
        <DocsCallout variant="tip">
          AI feedback consumes ~30s of AI hours per story. The first story per session uses your free
          allowance; subsequent ones come from your subscription pool.
        </DocsCallout>
      </section>

      <section id="how-grading-works" className="mb-10 scroll-mt-24">
        <h2 className="text-2xl font-bold mb-3">How grading works</h2>
        <p className="text-[15px] leading-relaxed" style={{ color: 'var(--text-secondary)' }}>
          For DSA: your code runs against test cases server-side. Pass / fail with stack trace shown for
          failures. For system design: AI compares your written architecture against the canonical solution
          and surfaces gaps. For behavioral: AI scores your STAR completeness on rubric dimensions.
        </p>
      </section>
    </DocsPageLayout>
  );
}
