import { Router } from 'express';
import crypto from 'crypto';
import fs from 'fs';
import path from 'path';
import * as eraser from '../services/eraser.js';
import * as pythonDiagrams from '../services/pythonDiagrams.js';
import { AppError, ErrorCode } from '../middleware/errorHandler.js';
import * as freeUsageService from '../services/freeUsageService.js';
import { query } from '../lib/shared-db.js';
import { recordUsage } from '../services/aiHoursMeter.js';
import { hourBudgetGate } from '../middleware/hourBudgetGate.js';

const router = Router();

// Daily diagram cap for paid users to prevent abuse
const PAID_DIAGRAM_DAILY_LIMIT = 50;
const dailyDiagramUsage = new Map();

function checkDailyDiagramLimit(userId) {
  const today = new Date().toISOString().slice(0, 10);
  const key = `${userId}:${today}`;
  const count = dailyDiagramUsage.get(key) || 0;
  if (count >= PAID_DIAGRAM_DAILY_LIMIT) return false;
  dailyDiagramUsage.set(key, count + 1);
  // Clean old entries daily
  if (dailyDiagramUsage.size > 10000) {
    for (const [k] of dailyDiagramUsage) {
      if (!k.endsWith(today)) dailyDiagramUsage.delete(k);
    }
  }
  return true;
}

/** Hash a problem description into a stable cache key */
function hashProblem(text) {
  return crypto.createHash('sha256').update(text.trim().toLowerCase()).digest('hex').slice(0, 32);
}

/**
 * Owner/admin gate for diagram *generation* (not lookup).
 *
 * Policy: regular users must consume pre-generated diagrams from the cache.
 * Only owners/admins may trigger fresh generation — they pre-warm topics
 * ahead of time. This keeps Anthropic spend bounded and predictable.
 *
 * Source of truth is OWNER_EMAILS env (same list hourBudgetGate.js uses,
 * default chundubabu@gmail.com,babuchundu@gmail.com). Also accepts
 * req.user.is_admin = true if the lumora authenticate middleware set it.
 *
 * NOTE: ascend-backend's jwtAuth doesn't currently populate is_admin, so
 * the email check is the load-bearing path. If a future migration sets
 * req.user.is_admin from users.is_admin, this still works.
 */
const OWNER_EMAILS = new Set(
  ((process.env.OWNER_EMAILS || process.env.ADMIN_EMAILS || '')
    .split(',').map((e) => e.trim().toLowerCase()).filter(Boolean)),
);
function isAdminUser(user) {
  if (!user) return false;
  if (user.is_admin === true) return true;
  return !!user.email && OWNER_EMAILS.has(String(user.email).toLowerCase());
}
function adminOnlyForGeneration(req, res, next) {
  if (!isAdminUser(req.user)) {
    return res.status(403).json({
      error: 'Diagrams are pre-generated by the team. If a problem is missing its diagram, it will be added soon.',
      code: 'ADMIN_ONLY',
    });
  }
  next();
}

/**
 * POST /api/diagram/eraser/lookup
 * Cache-only lookup for Eraser diagrams — never generates, never costs
 * Eraser API credits. Open to all authed users (not admin-only) so the
 * panel can transparently prefer a pre-generated Eraser diagram over
 * Graphviz on auto-load. Returns 404 when nothing cached.
 *
 * Mirrors POST /api/diagram/lookup (Graphviz cache-only) — kept as a
 * separate route because Eraser cache rows have a distinct hash shape
 * (`description::eraser::default::detailLevel`).
 */
router.post('/eraser/lookup', async (req, res) => {
  try {
    const { description, detailLevel = 'overview', cacheKey } = req.body || {};
    if (!description) {
      return res.status(400).json({ error: 'Description required' });
    }
    const problemHash = hashProblem(`${cacheKey || description}::eraser::default::${detailLevel}`);
    const result = await query(
      'SELECT image_url, edit_url FROM ascend_diagram_cache WHERE problem_hash = $1 AND image_url IS NOT NULL LIMIT 1',
      [problemHash],
    );
    if (result.rows.length === 0) {
      // 200 with cached:false instead of 404 — keeps Chrome's console
      // clean. The frontend already treats {cached: false} as "no
      // cache, fall through to Graphviz" regardless of status code,
      // so no behavior change beyond the HTTP status.
      return res.json({ cached: false });
    }
    res.json({
      imageUrl: result.rows[0].image_url,
      editUrl: result.rows[0].edit_url,
      cached: true,
    });
  } catch (err) {
    console.error('[EraserLookup] error:', err);
    res.status(500).json({ error: 'Eraser lookup failed' });
  }
});

/**
 * POST /api/diagram/eraser
 * Generate an architecture diagram using Eraser.io (with DB caching)
 */
router.post('/eraser', adminOnlyForGeneration, hourBudgetGate, async (req, res, next) => {
  try {
    const { description, detailLevel = 'overview', cacheKey } = req.body;

    if (!description) {
      throw new AppError(
        'Description is required',
        ErrorCode.VALIDATION_ERROR,
        'Please provide a system design description'
      );
    }

    // Hash on stable cacheKey with eraser-specific dimensions
    const problemHash = hashProblem(`${cacheKey || description}::eraser::default::${detailLevel}`);

    // 1. Check cache first
    try {
      const cached = await query(
        'SELECT image_url, edit_url FROM ascend_diagram_cache WHERE problem_hash = $1',
        [problemHash]
      );
      if (cached.rows.length > 0) {
        console.log('[DiagramCache] Eraser cache hit for hash:', problemHash);
        return res.json({
          imageUrl: cached.rows[0].image_url,
          editUrl: cached.rows[0].edit_url,
          cached: true,
        });
      }
    } catch {
      // Cache lookup failed (table might not exist yet) — fall through to generate
    }

    // 2. Check free usage
    const userId = req.user?.id;
    const isAdmin = req.user?.is_admin;
    if (userId && !isAdmin) {
      const canUse = await freeUsageService.canUseFeature(userId, 'design');
      if (!canUse.allowed) {
        return res.status(429).json({ error: canUse.reason || 'Free trial exhausted.', subscriptionRequired: true });
      }
      if (canUse.hasSubscription && !checkDailyDiagramLimit(userId)) {
        return res.status(429).json({ error: `Daily diagram limit reached (${PAID_DIAGRAM_DAILY_LIMIT}/day). Try again tomorrow.`, dailyLimitReached: true });
      }
    }

    // 3. Check if Eraser is configured
    if (!eraser.isConfigured()) {
      throw new AppError(
        'Eraser API not configured',
        ErrorCode.EXTERNAL_API_ERROR,
        'ERASER_API_KEY environment variable is not set'
      );
    }

    // 4. Generate via Eraser API
    const result = await eraser.generateDiagram(description);

    // 5. Save to cache
    try {
      await query(
        `INSERT INTO ascend_diagram_cache (problem_hash, detail_level, image_url, edit_url, description)
         VALUES ($1, $2, $3, $4, $5)
         ON CONFLICT (problem_hash) DO UPDATE SET image_url = $3, edit_url = $4`,
        [problemHash, detailLevel, result.imageUrl, result.editUrl || null, description.slice(0, 500)]
      );
    } catch (err) {
      console.warn('[DiagramCache] Failed to save:', err.message);
    }

    res.json(result);
  } catch (error) {
    if (error instanceof AppError) {
      next(error);
    } else {
      next(new AppError(
        error.message || 'Failed to generate diagram',
        ErrorCode.EXTERNAL_API_ERROR,
        error.message
      ));
    }
  }
});

/**
 * POST /api/diagram/generate
 * Generate a cloud architecture diagram using Python diagrams library (with DB caching)
 */
router.post('/generate', adminOnlyForGeneration, hourBudgetGate, async (req, res, next) => {
  req.setTimeout(120000);
  res.setTimeout(120000);
  try {
    const { question, cloudProvider, difficulty, category, format, cacheKey, designKind: explicitDesignKind } = req.body;
    const provider = cloudProvider || 'auto';
    // Direction + detail are now driven by the frontend. The earlier
    // server-side lock to TB/detailed silently overrode the panel's
    // LR/overview defaults, producing the dense vertical layout users
    // complained about. Frontend defaults to overview/LR but a stale
    // client may still send TB/detailed — both are valid combos. Cache
    // hash includes both, so each combo gets its own row.
    const ALLOWED_DIRECTIONS = new Set(['TB', 'LR']);
    const ALLOWED_DETAIL_LEVELS = new Set(['overview', 'detailed']);
    const direction = ALLOWED_DIRECTIONS.has(req.body.direction) ? req.body.direction : 'LR';
    const detailLevel = ALLOWED_DETAIL_LEVELS.has(req.body.detailLevel) ? req.body.detailLevel : 'overview';

    if (!question) {
      throw new AppError('Question is required', ErrorCode.VALIDATION_ERROR);
    }

    // Resolve archetype: question-text cues win over frontend hint.
    // Frontend hint is a fallback for ambiguous questions (e.g. "design
    // Twitter" → no cue → use the page-default 'system'). See
    // designKindClassifier.js for the priority order.
    const { classifyDesignKind } = await import('../services/designKindClassifier.js');
    const designKind = classifyDesignKind(question, explicitDesignKind);

    // 1. Check DB cache first — cached diagrams cost nothing to serve.
    // Only treat a row as a hit when we actually have a PNG (image_url or
    // image_data). Cache key includes designKind so an LRU-cache
    // class-diagram doesn't collide with a Twitter system-architecture
    // diagram on the same hash bucket.
    const problemHash = hashProblem(`${cacheKey || question}::${provider}::${direction}::${detailLevel}::${designKind}`);
    try {
      const cached = await query(
        'SELECT image_url, image_data IS NOT NULL AS has_image_data FROM ascend_diagram_cache WHERE problem_hash = $1 AND (image_url IS NOT NULL OR image_data IS NOT NULL)',
        [problemHash]
      );
      if (cached.rows.length > 0) {
        console.log('[DiagramCache] Cache hit for hash:', problemHash);
        return res.json({
          success: true,
          image_url: cached.rows[0].image_url,
          cloud_provider: provider,
          cached: true,
        });
      }
    } catch { /* table might not exist yet */ }

    // 2. Check free usage — only for cache misses (actual generation costs money)
    const userId = req.user?.id;
    const isAdmin = req.user?.is_admin;
    if (userId && !isAdmin) {
      const canUse = await freeUsageService.canUseFeature(userId, 'design');
      if (!canUse.allowed) {
        return res.status(429).json({ error: canUse.reason || 'Free trial exhausted.', subscriptionRequired: true });
      }
      if (canUse.hasSubscription && !checkDailyDiagramLimit(userId)) {
        return res.status(429).json({ error: `Daily diagram limit reached (${PAID_DIAGRAM_DAILY_LIMIT}/day). Try again tomorrow.`, dailyLimitReached: true });
      }
    }

    // 3. Check if configured
    if (!pythonDiagrams.isConfigured()) {
      throw new AppError('Diagram generation not configured — ANTHROPIC_API_KEY is not set', ErrorCode.EXTERNAL_API_ERROR);
    }

    // 4. Generate via Python diagrams (Graphviz). The previous Mermaid
    // fallback violated the "No Mermaid Diagrams" + "No Text Arrow Diagrams"
    // rules — text-graph fallback was confusing for users, and admins can
    // simply retry once Python is back. If Python fails, we surface the
    // error and let the admin act, rather than silently degrading.
    const genStartedAt = new Date();
    let pythonResult = null;
    let pythonError = null;
    try {
      pythonResult = await pythonDiagrams.generateDiagram({
        question,
        cloudProvider: provider,
        difficulty: difficulty || 'medium',
        category: category || 'System Design',
        format: format || 'png',
        detailLevel,
        direction,
        designKind,
      });
      if (!pythonResult.success) {
        pythonError = pythonResult.error || 'Diagram generation failed';
        pythonResult = null;
      }
    } catch (err) {
      pythonError = err.message || 'Python diagram generation failed';
      console.warn('[Diagram] Python generation failed:', pythonError);
    }

    if (!pythonResult) {
      throw new AppError(
        pythonError || 'Diagram generation failed',
        ErrorCode.EXTERNAL_API_ERROR,
        'Python diagram generation failed'
      );
    }

    // 5. Read PNG into buffer and persist in DB (Python succeeded)
    const imageUrl = `/api/diagram/image/${problemHash}`;
    try {
      const filePath = path.join(pythonDiagrams.getOutputDir(), path.basename(pythonResult.image_url));
      const imageBuffer = fs.readFileSync(filePath);
      await query(
        `INSERT INTO ascend_diagram_cache (problem_hash, detail_level, cloud_provider, direction, image_url, image_data, description)
         VALUES ($1, $2, $3, $4, $5, $6, $7)
         ON CONFLICT (problem_hash) DO UPDATE SET image_url = $5, image_data = $6`,
        [problemHash, detailLevel, provider, direction, imageUrl, imageBuffer, (cacheKey || question).slice(0, 500)]
      );
      // Clean up temp file — image is now in DB
      try { fs.unlinkSync(filePath); } catch { /* ignore */ }
      console.log('[DiagramCache] Stored in DB, hash:', problemHash, 'size:', imageBuffer.length);
    } catch (err) {
      console.warn('[DiagramCache] Failed to persist image:', err.message);
      // Fall back to temp file URL if DB storage fails
      return res.json({ ...pythonResult, cloud_provider: provider });
    }

    if (req.user?.id) {
      // Diagram generation is dominated by Python+Anthropic wall time, not
      // output tokens. Charge the meter the actual elapsed seconds — a
      // clean attempt-1 run charges ~15s, a retry cascade charges ~45s.
      // This makes today's alias-map and provider-lock cost wins visible
      // on the meter instead of being flattened to a hardcoded 30s.
      recordUsage({
        userId: req.user.id,
        surface: 'capra_diagram',
        seconds: (Date.now() - genStartedAt.getTime()) / 1000,
        tokensIn: Math.ceil((question || '').length / 4),
        tokensOut: 0,
        model: 'claude-sonnet-4-6',
        startedAt: genStartedAt,
      });
    }
    res.json({ success: true, image_url: imageUrl, cloud_provider: provider, cached: false });
  } catch (error) {
    if (error instanceof AppError) {
      next(error);
    } else {
      next(new AppError(error.message || 'Failed to generate diagram', ErrorCode.EXTERNAL_API_ERROR, error.message));
    }
  }
});

const DOT_SYSTEM_PROMPT = `You are an expert cloud architect. Generate a pure Graphviz DOT diagram with an enterprise whiteboard style.

OUTPUT: Raw DOT source ONLY — no markdown fences, no explanations, just the digraph block.

REQUIRED SKELETON:
digraph G {
  graph [rankdir=LR bgcolor=white fontname="Helvetica" nodesep=0.5 ranksep=0.8 dpi=200 splines=ortho pad="0.6,0.6"]
  node  [fontname="Helvetica" fontsize=11 margin="0.22,0.10" style="rounded,filled" penwidth=1.5 shape=box]
  edge  [fontname="Helvetica" fontsize=9 color="#94a3b8" arrowsize=0.8 penwidth=1.2]

  clients [label="Clients\\n(Web / Mobile)" fillcolor="#f0f9ff" color="#0284c7" fontcolor="#0c4a6e"]

  subgraph cluster_edge {
    label="Edge / CDN"
    graph [bgcolor="#eff6ff" pencolor="#3b82f6" fontcolor="#1e3a8a" fontsize=11 fontname="Helvetica-Bold" style=rounded penwidth=1.8]
    cdn [label="CDN" fillcolor="#dbeafe" color="#3b5bdb" fontcolor="#1e3a5f"]
    lb  [label="Load\\nBalancer" fillcolor="#dbeafe" color="#3b5bdb" fontcolor="#1e3a5f"]
  }

  subgraph cluster_app {
    label="Application"
    graph [bgcolor="#f0fdf4" pencolor="#15803d" fontcolor="#14532d" fontsize=11 fontname="Helvetica-Bold" style=rounded penwidth=1.8]
    api [label="API\\nGateway" fillcolor="#dcfce7" color="#16a34a" fontcolor="#14532d"]
    svc [label="App\\nService" fillcolor="#dcfce7" color="#16a34a" fontcolor="#14532d"]
  }

  subgraph cluster_data {
    label="Data"
    graph [bgcolor="#fffbeb" pencolor="#b45309" fontcolor="#78350f" fontsize=11 fontname="Helvetica-Bold" style=rounded penwidth=1.8]
    db    [label="Primary\\nDB" fillcolor="#fef3c7" color="#d97706" fontcolor="#78350f"]
    cache [label="Cache" fillcolor="#fef3c7" color="#d97706" fontcolor="#78350f"]
  }

  clients -> cdn [label="HTTPS"]
  cdn -> lb
  lb -> api
  api -> svc
  svc -> db  [label="read/write"]
  svc -> cache [label="get/set"]
}

PALETTE — assign clusters based on function:
  Edge/CDN:      bgcolor=#eff6ff pencolor=#3b82f6  node fillcolor=#dbeafe color=#3b5bdb  fontcolor=#1e3a5f
  Application:   bgcolor=#f0fdf4 pencolor=#15803d  node fillcolor=#dcfce7 color=#16a34a  fontcolor=#14532d
  Data/Storage:  bgcolor=#fffbeb pencolor=#b45309  node fillcolor=#fef3c7 color=#d97706  fontcolor=#78350f
  Async/Queue:   bgcolor=#fdf4ff pencolor=#7c3aed  node fillcolor=#f3e8ff color=#9333ea  fontcolor=#4c1d95
  Observability: bgcolor=#fff1f2 pencolor=#be123c  node fillcolor=#ffe4e6 color=#e11d48  fontcolor=#881337

RULES:
- rankdir=LR is MANDATORY — never TB
- 8-14 nodes total — do not over-engineer
- SHORT labels: 2-3 words max, use \\n for line breaks
- Edge labels ONLY on the 3-5 most important paths (auth, cache miss, write, stream, etc.)
- All node IDs must be valid DOT identifiers (letters/digits/underscore only)
- No HTML-like labels (<...>) — plain string labels only
- splines=ortho for clean right-angle routing`;

/**
 * POST /api/diagram/generate-dot
 * Generate a pure Graphviz DOT architecture diagram (enterprise whiteboard style).
 * Uses Claude to generate DOT source, then renders via ai-services /diagram/render-dot.
 * Cached with dot: prefix to avoid collision with Python diagram cache.
 */
router.post('/generate-dot', adminOnlyForGeneration, hourBudgetGate, async (req, res, next) => {
  req.setTimeout(90000);
  res.setTimeout(90000);
  try {
    const { question, cloudProvider } = req.body;
    if (!question) return res.status(400).json({ error: 'question is required' });
    const provider = cloudProvider || 'aws';
    const problemHash = hashProblem(`dot:${question}::${provider}`);

    // 1. Check cache
    try {
      const cached = await query(
        'SELECT image_data IS NOT NULL AS has_image FROM ascend_diagram_cache WHERE problem_hash = $1 AND image_data IS NOT NULL',
        [problemHash],
      );
      if (cached.rows.length > 0) {
        return res.json({ success: true, image_url: `/api/diagram/image/${problemHash}`, cloud_provider: provider, cached: true });
      }
    } catch { /* table may not exist */ }

    // 2. Generate DOT via Claude
    const { default: Anthropic } = await import('@anthropic-ai/sdk');
    const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
    let _step = 'claude';
    const msg = await client.messages.create({
      model: 'claude-haiku-4-5-20251001',
      max_tokens: 2048,
      system: DOT_SYSTEM_PROMPT,
      messages: [{
        role: 'user',
        content: `Generate a Graphviz DOT architecture diagram for this system design question:\n\n"${question}"\n\nCloud provider preference: ${provider}\n\nReturn ONLY the raw digraph DOT source — no fences, no explanations.`,
      }],
    });

    let dotSource = msg.content[0].text.trim();
    // Strip any accidental markdown fences
    dotSource = dotSource.replace(/^```[^\n]*\n?/, '').replace(/\n?```$/, '').trim();
    if (!dotSource.startsWith('digraph')) {
      const idx = dotSource.indexOf('digraph');
      if (idx !== -1) dotSource = dotSource.slice(idx);
      else throw new Error('Claude did not produce a valid DOT digraph');
    }

    // 3. Render DOT locally — graphviz is pre-installed on the ascend-backend
    //    Railway container (Nixpacks graphviz package), no ai-services hop needed.
    //    execFileSync (not promisify(execFile)) is required because only the Sync
    //    variants forward `input` as stdin data to the child process.
    _step = 'render';
    const { execFileSync } = await import('child_process');
    const pngBuffer = execFileSync('dot', ['-Tpng', '-Gdpi=150'], {
      input: dotSource,
      timeout: 15000,
      maxBuffer: 8 * 1024 * 1024,
    });

    // 4. Cache in DB
    _step = 'db';
    const imageUrl = `/api/diagram/image/${problemHash}`;
    await query(
      `INSERT INTO ascend_diagram_cache (problem_hash, detail_level, cloud_provider, direction, image_url, image_data, description)
       VALUES ($1, 'overview', $2, 'LR', $3, $4, $5)
       ON CONFLICT (problem_hash) DO UPDATE SET image_url = $3, image_data = $4`,
      [problemHash, provider, imageUrl, pngBuffer, question.slice(0, 500)],
    );

    res.json({ success: true, image_url: imageUrl, cloud_provider: provider, cached: false });
  } catch (err) {
    console.error('[generate-dot] ERROR at step=', typeof _step !== 'undefined' ? _step : 'init', err?.message);
    return res.status(500).json({ error: err?.message || 'Unknown error', step: typeof _step !== 'undefined' ? _step : 'init' });
  }
});

/**
 * POST /api/diagram/lookup
 * Cache-only lookup — never generates. Returns cached diagram or 404.
 * Used by frontend during interviews to avoid expensive generation.
 */
router.post('/lookup', async (req, res) => {
  try {
    const { question, cloudProvider = 'auto', designKind: explicitDesignKind } = req.body;
    if (!question) return res.status(400).json({ error: 'Question required' });

    // Direction + detail come from the request body — must match the
    // hash computed by /generate or the lookup will miss the row that
    // /generate just wrote. Falls back to overview/LR if the caller
    // didn't supply them, matching /generate's default-resolution.
    const ALLOWED_DIRECTIONS = new Set(['TB', 'LR']);
    const ALLOWED_DETAIL_LEVELS = new Set(['overview', 'detailed']);
    const direction = ALLOWED_DIRECTIONS.has(req.body.direction) ? req.body.direction : 'LR';
    const detailLevel = ALLOWED_DETAIL_LEVELS.has(req.body.detailLevel) ? req.body.detailLevel : 'overview';
    // Resolve archetype to match the hash that /generate writes.
    const { classifyDesignKind } = await import('../services/designKindClassifier.js');
    const designKind = classifyDesignKind(question, explicitDesignKind);
    const providers = cloudProvider === 'auto' ? ['auto'] : [cloudProvider, 'auto'];
    const tried = new Set();

    for (const p of providers) {
      const hash = hashProblem(`${question}::${p}::${direction}::${detailLevel}::${designKind}`);
      if (tried.has(hash)) continue;
      tried.add(hash);

      const result = await query(
        'SELECT image_url, (image_data IS NOT NULL) AS has_blob FROM ascend_diagram_cache WHERE problem_hash = $1 AND (image_url IS NOT NULL OR image_data IS NOT NULL) LIMIT 1',
        [hash]
      );

      if (result.rows.length > 0 && result.rows[0].image_url) {
        let image_url = result.rows[0].image_url;
        if (image_url.startsWith('/static/') && result.rows[0].has_blob) {
          image_url = `/api/diagram/image/${hash}`;
        }
        console.log(`[DiagramLookup] Cache hit for: ${question.slice(0, 50)} (${p}/${direction}/${detailLevel})`);
        return res.json({ success: true, image_url, cached: true });
      }
    }

    console.log(`[DiagramLookup] No cache for: ${question.slice(0, 50)}`);
    res.json({ success: false, cached: false });
  } catch (err) {
    console.error('[DiagramLookup] error:', err);
    res.json({ success: false, error: 'Diagram lookup failed' });
  }
});

/**
 * DELETE /api/diagram/cache
 * Admin-only — purge cache rows by provider/direction/detail filters so they
 * regenerate on the next /generate call. Used after a code fix that changes
 * generated content (e.g. provider lock, alias map) to invalidate stale rows
 * without nuking the entire cache.
 *
 * Body filters (all optional, AND-combined). At least one MUST be set so we
 * don't accidentally truncate the table:
 *   { provider: 'aws'|'gcp'|'azure'|'auto', direction: 'LR'|'TB',
 *     detailLevel: 'overview'|'detailed', match: '<substring of question>' }
 *
 * Returns: { deleted: <row count> }
 */
router.delete('/cache', adminOnlyForGeneration, async (req, res) => {
  try {
    const { provider, direction, detailLevel, match } = req.body || {};
    const conds = [];
    const args = [];
    if (provider) { conds.push(`cloud_provider = $${conds.length + 1}`); args.push(provider); }
    if (direction) { conds.push(`direction = $${conds.length + 1}`); args.push(direction); }
    if (detailLevel) { conds.push(`detail_level = $${conds.length + 1}`); args.push(detailLevel); }
    if (match) { conds.push(`description ILIKE $${conds.length + 1}`); args.push(`%${match}%`); }
    if (conds.length === 0) {
      return res.status(400).json({ error: 'At least one filter required (provider/direction/detailLevel/match)', code: 'NO_FILTER' });
    }
    const sql = `DELETE FROM ascend_diagram_cache WHERE ${conds.join(' AND ')}`;
    const r = await query(sql, args);
    res.json({ deleted: r.rowCount, sql, args });
  } catch (err) {
    console.error('[DiagramCacheDelete] error:', err);
    res.status(500).json({ error: 'Cache delete failed', detail: err.message });
  }
});

/**
 * GET /api/diagram/cache-stats
 * Debug: show what's in the diagram cache
 */
router.get('/cache-stats', async (req, res) => {
  try {
    const stats = await query(`
      SELECT problem_hash, description, detail_level, cloud_provider, direction,
             image_url IS NOT NULL as has_url,
             image_data IS NOT NULL as has_data
      FROM ascend_diagram_cache
      ORDER BY problem_hash
      LIMIT 50
    `);
    res.json({ count: stats.rows.length, diagrams: stats.rows });
  } catch (err) {
    console.error('[DiagramCacheStats] error:', err);
    res.json({ error: 'Cache stats unavailable' });
  }
});

/**
 * GET /api/diagram/status
 * Check if diagram services are configured
 */
router.get('/status', (req, res) => {
  res.json({
    eraser: eraser.isConfigured(),
    pythonDiagrams: pythonDiagrams.isConfigured()
  });
});

/**
 * GET /api/diagram/debug
 * Debug endpoint to check Python/graphviz installation
 */
router.get('/debug', async (req, res) => {
  const { spawn } = await import('child_process');
  const results = {
    python: { available: false, version: null, error: null },
    graphviz: { available: false, version: null, error: null },
    diagrams: { available: false, error: null },
    diagramEnginePath: pythonDiagrams.getOutputDir ? pythonDiagrams.getOutputDir() : 'unknown'
  };

  // Check Python
  try {
    const python = spawn('python3', ['--version']);
    let stdout = '';
    let stderr = '';
    python.stdout.on('data', d => stdout += d);
    python.stderr.on('data', d => stderr += d);
    await new Promise((resolve) => {
      python.on('close', (code) => {
        results.python.available = code === 0;
        results.python.version = (stdout || stderr).trim();
        resolve();
      });
      python.on('error', (err) => {
        results.python.error = err.message;
        resolve();
      });
    });
  } catch (e) {
    results.python.error = e.message;
  }

  // Check graphviz (dot command)
  try {
    const dot = spawn('dot', ['-V']);
    let stderr = '';
    dot.stderr.on('data', d => stderr += d);
    await new Promise((resolve) => {
      dot.on('close', (code) => {
        results.graphviz.available = code === 0;
        results.graphviz.version = stderr.trim();
        resolve();
      });
      dot.on('error', (err) => {
        results.graphviz.error = err.message;
        resolve();
      });
    });
  } catch (e) {
    results.graphviz.error = e.message;
  }

  // Check diagrams library
  try {
    const python = spawn('python3', ['-c', 'import diagrams; print("OK")']);
    let stdout = '';
    let stderr = '';
    python.stdout.on('data', d => stdout += d);
    python.stderr.on('data', d => stderr += d);
    await new Promise((resolve) => {
      python.on('close', (code) => {
        results.diagrams.available = code === 0 && stdout.includes('OK');
        if (stderr) results.diagrams.error = stderr.trim();
        resolve();
      });
      python.on('error', (err) => {
        results.diagrams.error = err.message;
        resolve();
      });
    });
  } catch (e) {
    results.diagrams.error = e.message;
  }

  res.json(results);
});

export default router;
