import { Router } from 'express';
import crypto from 'crypto';
import fs from 'fs';
import path from 'path';
import * as eraser from '../services/eraser.js';
import * as pythonDiagrams from '../services/pythonDiagrams.js';
import { AppError, ErrorCode } from '../middleware/errorHandler.js';
import * as freeUsageService from '../services/freeUsageService.js';
import { query } from '../lib/shared-db.js';
import { recordUsage } from '../services/aiHoursMeter.js';
import { hourBudgetGate } from '../middleware/hourBudgetGate.js';

const router = Router();

// Daily diagram cap for paid users to prevent abuse
const PAID_DIAGRAM_DAILY_LIMIT = 50;
const dailyDiagramUsage = new Map();

function checkDailyDiagramLimit(userId) {
  const today = new Date().toISOString().slice(0, 10);
  const key = `${userId}:${today}`;
  const count = dailyDiagramUsage.get(key) || 0;
  if (count >= PAID_DIAGRAM_DAILY_LIMIT) return false;
  dailyDiagramUsage.set(key, count + 1);
  // Clean old entries daily
  if (dailyDiagramUsage.size > 10000) {
    for (const [k] of dailyDiagramUsage) {
      if (!k.endsWith(today)) dailyDiagramUsage.delete(k);
    }
  }
  return true;
}

/** Hash a problem description into a stable cache key */
function hashProblem(text) {
  return crypto.createHash('sha256').update(text.trim().toLowerCase()).digest('hex').slice(0, 32);
}

/**
 * Owner/admin gate for diagram *generation* (not lookup).
 *
 * Policy: regular users must consume pre-generated diagrams from the cache.
 * Only owners/admins may trigger fresh generation — they pre-warm topics
 * ahead of time. This keeps Anthropic spend bounded and predictable.
 *
 * Source of truth is OWNER_EMAILS env (same list hourBudgetGate.js uses,
 * default chundubabu@gmail.com,babuchundu@gmail.com). Also accepts
 * req.user.is_admin = true if the lumora authenticate middleware set it.
 *
 * NOTE: ascend-backend's jwtAuth doesn't currently populate is_admin, so
 * the email check is the load-bearing path. If a future migration sets
 * req.user.is_admin from users.is_admin, this still works.
 */
const OWNER_EMAILS = new Set(
  ((process.env.OWNER_EMAILS || process.env.ADMIN_EMAILS || 'chundubabu@gmail.com,babuchundu@gmail.com')
    .split(',').map((e) => e.trim().toLowerCase()).filter(Boolean)),
);
function isAdminUser(user) {
  if (!user) return false;
  if (user.is_admin === true) return true;
  return !!user.email && OWNER_EMAILS.has(String(user.email).toLowerCase());
}
function adminOnlyForGeneration(req, res, next) {
  if (!isAdminUser(req.user)) {
    return res.status(403).json({
      error: 'Diagrams are pre-generated by the team. If a problem is missing its diagram, it will be added soon.',
      code: 'ADMIN_ONLY',
    });
  }
  next();
}

/**
 * POST /api/diagram/eraser
 * Generate an architecture diagram using Eraser.io (with DB caching)
 */
router.post('/eraser', adminOnlyForGeneration, hourBudgetGate, async (req, res, next) => {
  try {
    const { description, detailLevel = 'overview', cacheKey } = req.body;

    if (!description) {
      throw new AppError(
        'Description is required',
        ErrorCode.VALIDATION_ERROR,
        'Please provide a system design description'
      );
    }

    // Hash on stable cacheKey with eraser-specific dimensions
    const problemHash = hashProblem(`${cacheKey || description}::eraser::default::${detailLevel}`);

    // 1. Check cache first
    try {
      const cached = await query(
        'SELECT image_url, edit_url FROM ascend_diagram_cache WHERE problem_hash = $1',
        [problemHash]
      );
      if (cached.rows.length > 0) {
        console.log('[DiagramCache] Eraser cache hit for hash:', problemHash);
        return res.json({
          imageUrl: cached.rows[0].image_url,
          editUrl: cached.rows[0].edit_url,
          cached: true,
        });
      }
    } catch {
      // Cache lookup failed (table might not exist yet) — fall through to generate
    }

    // 2. Check free usage
    const userId = req.user?.id;
    const isAdmin = req.user?.is_admin;
    if (userId && !isAdmin) {
      const canUse = await freeUsageService.canUseFeature(userId, 'design');
      if (!canUse.allowed) {
        return res.status(429).json({ error: canUse.reason || 'Free trial exhausted.', subscriptionRequired: true });
      }
      if (canUse.hasSubscription && !checkDailyDiagramLimit(userId)) {
        return res.status(429).json({ error: `Daily diagram limit reached (${PAID_DIAGRAM_DAILY_LIMIT}/day). Try again tomorrow.`, dailyLimitReached: true });
      }
    }

    // 3. Check if Eraser is configured
    if (!eraser.isConfigured()) {
      throw new AppError(
        'Eraser API not configured',
        ErrorCode.EXTERNAL_API_ERROR,
        'ERASER_API_KEY environment variable is not set'
      );
    }

    // 4. Generate via Eraser API
    const result = await eraser.generateDiagram(description);

    // 5. Save to cache
    try {
      await query(
        `INSERT INTO ascend_diagram_cache (problem_hash, detail_level, image_url, edit_url, description)
         VALUES ($1, $2, $3, $4, $5)
         ON CONFLICT (problem_hash) DO UPDATE SET image_url = $3, edit_url = $4`,
        [problemHash, detailLevel, result.imageUrl, result.editUrl || null, description.slice(0, 500)]
      );
    } catch (err) {
      console.warn('[DiagramCache] Failed to save:', err.message);
    }

    res.json(result);
  } catch (error) {
    if (error instanceof AppError) {
      next(error);
    } else {
      next(new AppError(
        error.message || 'Failed to generate diagram',
        ErrorCode.EXTERNAL_API_ERROR,
        error.message
      ));
    }
  }
});

/**
 * POST /api/diagram/generate
 * Generate a cloud architecture diagram using Python diagrams library (with DB caching)
 */
router.post('/generate', adminOnlyForGeneration, hourBudgetGate, async (req, res, next) => {
  req.setTimeout(120000);
  res.setTimeout(120000);
  try {
    const { question, cloudProvider, difficulty, category, format, detailLevel = 'overview', direction = 'LR', cacheKey } = req.body;
    const provider = cloudProvider || 'auto';

    if (!question) {
      throw new AppError('Question is required', ErrorCode.VALIDATION_ERROR);
    }

    // 1. Check DB cache first — cached diagrams cost nothing to serve.
    // Only treat a row as a hit when we actually have a PNG (image_url or
    // image_data). A mermaid-only row means Python was down at cache time;
    // we'd rather pay to regenerate to PNG than permanently serve text.
    const problemHash = hashProblem(`${cacheKey || question}::${provider}::${direction}::${detailLevel}`);
    try {
      const cached = await query(
        'SELECT image_url, image_data IS NOT NULL AS has_image_data FROM ascend_diagram_cache WHERE problem_hash = $1 AND (image_url IS NOT NULL OR image_data IS NOT NULL)',
        [problemHash]
      );
      if (cached.rows.length > 0) {
        console.log('[DiagramCache] Cache hit for hash:', problemHash);
        return res.json({
          success: true,
          image_url: cached.rows[0].image_url,
          cloud_provider: provider,
          cached: true,
        });
      }
    } catch { /* table might not exist yet */ }

    // 2. Check free usage — only for cache misses (actual generation costs money)
    const userId = req.user?.id;
    const isAdmin = req.user?.is_admin;
    if (userId && !isAdmin) {
      const canUse = await freeUsageService.canUseFeature(userId, 'design');
      if (!canUse.allowed) {
        return res.status(429).json({ error: canUse.reason || 'Free trial exhausted.', subscriptionRequired: true });
      }
      if (canUse.hasSubscription && !checkDailyDiagramLimit(userId)) {
        return res.status(429).json({ error: `Daily diagram limit reached (${PAID_DIAGRAM_DAILY_LIMIT}/day). Try again tomorrow.`, dailyLimitReached: true });
      }
    }

    // 3. Check if configured
    if (!pythonDiagrams.isConfigured()) {
      throw new AppError('Diagram generation not configured — ANTHROPIC_API_KEY is not set', ErrorCode.EXTERNAL_API_ERROR);
    }

    // 4. Try Python diagrams first, fall back to Mermaid code generation.
    // Wall-clock starts here so the AI-hours meter reflects real generation
    // time (Python + retries + Mermaid fallback if it fires) instead of a
    // hardcoded 30s approximation.
    const genStartedAt = new Date();
    let pythonResult = null;
    let pythonError = null;
    try {
      pythonResult = await pythonDiagrams.generateDiagram({
        question,
        cloudProvider: provider,
        difficulty: difficulty || 'medium',
        category: category || 'System Design',
        format: format || 'png',
        detailLevel,
        direction,
      });
      if (!pythonResult.success) {
        pythonError = pythonResult.error || 'Diagram generation failed';
        pythonResult = null;
      }
    } catch (err) {
      pythonError = err.message || 'Python diagram generation failed';
      console.warn('[Diagram] Python generation failed, trying Mermaid fallback:', pythonError);
    }

    // Python failed — try Mermaid fallback
    if (!pythonResult) {
      console.warn('[Diagram] Python failed, trying Mermaid fallback:', pythonError);
      try {
        const { default: claude } = await import('../services/claude.js');
        const mermaidPrompt = `Generate a Mermaid.js architecture diagram for: ${question}
Provider: ${provider === 'auto' ? 'generic cloud' : provider}
Detail: ${detailLevel}
Direction: ${direction}

Return ONLY a valid Mermaid graph definition starting with "graph ${direction}" or "flowchart ${direction}". No markdown fences, no explanation. Use short node labels.`;
        const mermaidCode = await claude.generateText(mermaidPrompt, { maxTokens: 2000 });
        if (mermaidCode && mermaidCode.trim().length > 20) {
          // Cache the mermaid code
          try {
            await query(
              `INSERT INTO ascend_diagram_cache (problem_hash, detail_level, cloud_provider, direction, mermaid_code, description)
               VALUES ($1, $2, $3, $4, $5, $6)
               ON CONFLICT (problem_hash) DO UPDATE SET mermaid_code = $5`,
              [problemHash, detailLevel, provider, direction, mermaidCode.trim(), (cacheKey || question).slice(0, 500)]
            );
          } catch { /* ignore cache error */ }
          if (req.user?.id) {
            // Mermaid path — wall-clock covers the failed Python attempt(s)
            // plus the Mermaid retry. tokens kept for analytics, seconds is
            // the source of truth for the meter.
            recordUsage({
              userId: req.user.id,
              surface: 'capra_diagram',
              seconds: (Date.now() - genStartedAt.getTime()) / 1000,
              tokensIn: Math.ceil(mermaidPrompt.length / 4),
              tokensOut: Math.ceil(mermaidCode.length / 4),
              model: 'claude-sonnet-4-6',
              startedAt: genStartedAt,
            });
          }
          return res.json({ success: true, type: 'mermaid', mermaid_code: mermaidCode.trim(), cloud_provider: provider, cached: false });
        }
      } catch (mermaidErr) {
        console.error('[Diagram] Mermaid fallback also failed:', mermaidErr.message);
      }
      // Both failed
      throw new AppError(
        pythonError || 'Diagram generation failed',
        ErrorCode.EXTERNAL_API_ERROR,
        'Python and Mermaid fallback both failed'
      );
    }

    // 5. Read PNG into buffer and persist in DB (Python succeeded)
    const imageUrl = `/api/diagram/image/${problemHash}`;
    try {
      const filePath = path.join(pythonDiagrams.getOutputDir(), path.basename(pythonResult.image_url));
      const imageBuffer = fs.readFileSync(filePath);
      await query(
        `INSERT INTO ascend_diagram_cache (problem_hash, detail_level, cloud_provider, direction, image_url, image_data, description)
         VALUES ($1, $2, $3, $4, $5, $6, $7)
         ON CONFLICT (problem_hash) DO UPDATE SET image_url = $5, image_data = $6`,
        [problemHash, detailLevel, provider, direction, imageUrl, imageBuffer, (cacheKey || question).slice(0, 500)]
      );
      // Clean up temp file — image is now in DB
      try { fs.unlinkSync(filePath); } catch { /* ignore */ }
      console.log('[DiagramCache] Stored in DB, hash:', problemHash, 'size:', imageBuffer.length);
    } catch (err) {
      console.warn('[DiagramCache] Failed to persist image:', err.message);
      // Fall back to temp file URL if DB storage fails
      return res.json({ ...pythonResult, cloud_provider: provider });
    }

    if (req.user?.id) {
      // Diagram generation is dominated by Python+Anthropic wall time, not
      // output tokens. Charge the meter the actual elapsed seconds — a
      // clean attempt-1 run charges ~15s, a retry cascade charges ~45s.
      // This makes today's alias-map and provider-lock cost wins visible
      // on the meter instead of being flattened to a hardcoded 30s.
      recordUsage({
        userId: req.user.id,
        surface: 'capra_diagram',
        seconds: (Date.now() - genStartedAt.getTime()) / 1000,
        tokensIn: Math.ceil((question || '').length / 4),
        tokensOut: 0,
        model: 'claude-sonnet-4-6',
        startedAt: genStartedAt,
      });
    }
    res.json({ success: true, image_url: imageUrl, cloud_provider: provider, cached: false });
  } catch (error) {
    if (error instanceof AppError) {
      next(error);
    } else {
      next(new AppError(error.message || 'Failed to generate diagram', ErrorCode.EXTERNAL_API_ERROR, error.message));
    }
  }
});

/**
 * POST /api/diagram/lookup
 * Cache-only lookup — never generates. Returns cached diagram or 404.
 * Used by frontend during interviews to avoid expensive generation.
 */
router.post('/lookup', async (req, res) => {
  try {
    const { question, cloudProvider = 'auto', detailLevel = 'overview', direction = 'TB' } = req.body;
    if (!question) return res.status(400).json({ error: 'Question required' });

    // Try multiple hash combinations across provider + direction only.
    // detailLevel is NOT iterated: when the user picks 'detailed', they want
    // detailed — returning a cached 'overview' would make the toggle look
    // broken. Provider/direction are visually similar enough that a cached
    // hit on a sibling key is still useful.
    const providers = [cloudProvider, 'auto'];
    const directions = [direction, direction === 'TB' ? 'LR' : 'TB'];
    const tried = new Set();

    for (const p of providers) {
      for (const d of directions) {
        const hash = hashProblem(`${question}::${p}::${d}::${detailLevel}`);
        if (tried.has(hash)) continue;
        tried.add(hash);

        // Prefer rows with a PNG (image_url/image_data). Mermaid-only rows
        // are a cached fallback from a Python outage — only return them
        // when nothing better is found.
        const result = await query(
          'SELECT image_url, mermaid_code FROM ascend_diagram_cache WHERE problem_hash = $1 AND (image_url IS NOT NULL OR image_data IS NOT NULL OR mermaid_code IS NOT NULL) ORDER BY (image_url IS NOT NULL OR image_data IS NOT NULL) DESC LIMIT 1',
          [hash]
        );

        if (result.rows.length > 0) {
          console.log(`[DiagramLookup] Cache hit for: ${question.slice(0, 50)} (${p}/${d}/${detailLevel})`);
          if (result.rows[0].image_url) {
            return res.json({ success: true, image_url: result.rows[0].image_url, cached: true });
          }
          if (result.rows[0].mermaid_code) {
            return res.json({ success: true, type: 'mermaid', mermaid_code: result.rows[0].mermaid_code, cached: true });
          }
        }
      }
    }

    console.log(`[DiagramLookup] No cache for: ${question.slice(0, 50)}`);
    res.json({ success: false, cached: false });
  } catch (err) {
    console.error('[DiagramLookup] error:', err);
    res.json({ success: false, error: 'Diagram lookup failed' });
  }
});

/**
 * DELETE /api/diagram/cache
 * Admin-only — purge cache rows by provider/direction/detail filters so they
 * regenerate on the next /generate call. Used after a code fix that changes
 * generated content (e.g. provider lock, alias map) to invalidate stale rows
 * without nuking the entire cache.
 *
 * Body filters (all optional, AND-combined). At least one MUST be set so we
 * don't accidentally truncate the table:
 *   { provider: 'aws'|'gcp'|'azure'|'auto', direction: 'LR'|'TB',
 *     detailLevel: 'overview'|'detailed', match: '<substring of question>' }
 *
 * Returns: { deleted: <row count> }
 */
router.delete('/cache', adminOnlyForGeneration, async (req, res) => {
  try {
    const { provider, direction, detailLevel, match } = req.body || {};
    const conds = [];
    const args = [];
    if (provider) { conds.push(`cloud_provider = $${conds.length + 1}`); args.push(provider); }
    if (direction) { conds.push(`direction = $${conds.length + 1}`); args.push(direction); }
    if (detailLevel) { conds.push(`detail_level = $${conds.length + 1}`); args.push(detailLevel); }
    if (match) { conds.push(`description ILIKE $${conds.length + 1}`); args.push(`%${match}%`); }
    if (conds.length === 0) {
      return res.status(400).json({ error: 'At least one filter required (provider/direction/detailLevel/match)', code: 'NO_FILTER' });
    }
    const sql = `DELETE FROM ascend_diagram_cache WHERE ${conds.join(' AND ')}`;
    const r = await query(sql, args);
    res.json({ deleted: r.rowCount, sql, args });
  } catch (err) {
    console.error('[DiagramCacheDelete] error:', err);
    res.status(500).json({ error: 'Cache delete failed', detail: err.message });
  }
});

/**
 * GET /api/diagram/cache-stats
 * Debug: show what's in the diagram cache
 */
router.get('/cache-stats', async (req, res) => {
  try {
    const stats = await query(`
      SELECT problem_hash, description, detail_level, cloud_provider, direction,
             image_url IS NOT NULL as has_url,
             image_data IS NOT NULL as has_data,
             mermaid_code IS NOT NULL as has_mermaid
      FROM ascend_diagram_cache
      ORDER BY problem_hash
      LIMIT 50
    `);
    res.json({ count: stats.rows.length, diagrams: stats.rows });
  } catch (err) {
    console.error('[DiagramCacheStats] error:', err);
    res.json({ error: 'Cache stats unavailable' });
  }
});

/**
 * GET /api/diagram/status
 * Check if diagram services are configured
 */
router.get('/status', (req, res) => {
  res.json({
    eraser: eraser.isConfigured(),
    pythonDiagrams: pythonDiagrams.isConfigured()
  });
});

/**
 * GET /api/diagram/debug
 * Debug endpoint to check Python/graphviz installation
 */
router.get('/debug', async (req, res) => {
  const { spawn } = await import('child_process');
  const results = {
    python: { available: false, version: null, error: null },
    graphviz: { available: false, version: null, error: null },
    diagrams: { available: false, error: null },
    diagramEnginePath: pythonDiagrams.getOutputDir ? pythonDiagrams.getOutputDir() : 'unknown'
  };

  // Check Python
  try {
    const python = spawn('python3', ['--version']);
    let stdout = '';
    let stderr = '';
    python.stdout.on('data', d => stdout += d);
    python.stderr.on('data', d => stderr += d);
    await new Promise((resolve) => {
      python.on('close', (code) => {
        results.python.available = code === 0;
        results.python.version = (stdout || stderr).trim();
        resolve();
      });
      python.on('error', (err) => {
        results.python.error = err.message;
        resolve();
      });
    });
  } catch (e) {
    results.python.error = e.message;
  }

  // Check graphviz (dot command)
  try {
    const dot = spawn('dot', ['-V']);
    let stderr = '';
    dot.stderr.on('data', d => stderr += d);
    await new Promise((resolve) => {
      dot.on('close', (code) => {
        results.graphviz.available = code === 0;
        results.graphviz.version = stderr.trim();
        resolve();
      });
      dot.on('error', (err) => {
        results.graphviz.error = err.message;
        resolve();
      });
    });
  } catch (e) {
    results.graphviz.error = e.message;
  }

  // Check diagrams library
  try {
    const python = spawn('python3', ['-c', 'import diagrams; print("OK")']);
    let stdout = '';
    let stderr = '';
    python.stdout.on('data', d => stdout += d);
    python.stderr.on('data', d => stderr += d);
    await new Promise((resolve) => {
      python.on('close', (code) => {
        results.diagrams.available = code === 0 && stdout.includes('OK');
        if (stderr) results.diagrams.error = stderr.trim();
        resolve();
      });
      python.on('error', (err) => {
        results.diagrams.error = err.message;
        resolve();
      });
    });
  } catch (e) {
    results.diagrams.error = e.message;
  }

  res.json(results);
});

export default router;
