#!/usr/bin/env python3
import graphviz, os

NODE = dict(shape='box', style='filled,rounded', fontname='Helvetica Neue',
            fontsize='12', penwidth='1.5', height='0.45', margin='0.15,0.08')
EDGE = dict(fontname='Helvetica Neue', fontsize='10', penwidth='1.5')
C = {
    'navy':   ('#dbeafe', '#3b82f6', '#1e40af'),
    'gold':   ('#fef3c7', '#f59e0b', '#92400e'),
    'green':  ('#dcfce7', '#22c55e', '#166534'),
    'red':    ('#fee2e2', '#ef4444', '#991b1b'),
    'purple': ('#e0e7ff', '#6366f1', '#3730a3'),
    'teal':   ('#ccfbf1', '#14b8a6', '#115e59'),
    'cyan':   ('#cffafe', '#06b6d4', '#155e75'),
    'gray':   ('#f3f4f6', '#6b7280', '#374151'),
}
def n(g, name, label, c='navy'):
    g.node(name, label, fillcolor=C[c][0], color=C[c][1], fontcolor=C[c][2], **NODE)
def e(g, a, b, label='', color='#475569', style='solid'):
    g.edge(a, b, label=f'  {label}  ' if label else '', color=color, fontcolor=color, style=style, **EDGE)
def base_graph(name, title, rankdir='LR'):
    g = graphviz.Digraph(name, format='png')
    g.attr(bgcolor='#ffffff', dpi='200', pad='0.25', nodesep='0.5', ranksep='0.45',
           splines='spline', rankdir=rankdir,
           label=f'  {title}  ', labelloc='t',
           fontsize='14', fontname='Helvetica Neue Bold', fontcolor='#1e293b')
    return g


OUT = os.path.join(os.path.dirname(__file__), '..', 'public', 'diagrams', 'cloud')
os.makedirs(OUT, exist_ok=True)


def diag_ec2_instance_lifecycle():
    g = base_graph('ec2_lifecycle', 'EC2 Instance Lifecycle — States and Transitions')
    n(g, 'pending',   'Pending\n(provisioning)', 'gray')
    n(g, 'running',   'Running\n(billed per second)', 'green')
    n(g, 'stopping',  'Stopping\n(EBS-backed only)', 'gold')
    n(g, 'stopped',   'Stopped\n(no compute bill;\nstorage billed)', 'gold')
    n(g, 'shutting',  'Shutting-down', 'red')
    n(g, 'terminated','Terminated\n(root EBS deleted\nby default)', 'red')
    n(g, 'rebooting', 'Rebooting\n(same host;\nno state loss)', 'navy')
    e(g, 'pending',  'running',   'launch complete')
    e(g, 'running',  'stopping',  'stop')
    e(g, 'stopping', 'stopped',   '')
    e(g, 'stopped',  'pending',   'start', '#22c55e')
    e(g, 'running',  'rebooting', 'reboot', '#6366f1')
    e(g, 'rebooting','running',   '')
    e(g, 'running',  'shutting',  'terminate', '#ef4444')
    e(g, 'stopped',  'shutting',  'terminate', '#ef4444')
    e(g, 'shutting', 'terminated','')
    g.render(os.path.join(OUT, 'aws-ec2-lifecycle'), cleanup=True)


def diag_ec2_purchasing():
    g = base_graph('ec2_purchasing', 'EC2 Purchasing Options — Cost vs Commitment', rankdir='TB')
    n(g, 'od',   'On-Demand\nPay per second\nNo commitment\nMax flexibility', 'navy')
    n(g, 'ri',   'Reserved Instances\n1- or 3-year term\n30–60% savings\nStandard or Convertible', 'green')
    n(g, 'sp',   'Savings Plans\nFlexible commitment\n($/hr spend)\nCovers EC2 + Fargate + Lambda', 'teal')
    n(g, 'spot', 'Spot Instances\nUp to 90% off\n2-min interruption notice\nFault-tolerant workloads only', 'gold')
    n(g, 'ded',  'Dedicated Hosts\nPhysical server\nlicensing compliance\nHighest cost', 'purple')
    n(g, 'base', 'Baseline (steady-state)\nproduction fleet', 'gray')
    n(g, 'burst','Burst / Batch\nCI runners, ML training', 'gray')
    e(g, 'base', 'ri',   'best savings', '#22c55e')
    e(g, 'base', 'sp',   'flexibility', '#14b8a6')
    e(g, 'burst','spot', 'max discount', '#f59e0b')
    e(g, 'burst','od',   'unpredictable', '#3b82f6')
    e(g, 'base', 'ded',  'licensing / compliance', '#6366f1')
    g.render(os.path.join(OUT, 'aws-ec2-purchasing'), cleanup=True)


def diag_lambda_invocation():
    g = base_graph('lambda_invocation', 'Lambda Invocation Models — Sync / Async / Stream')
    n(g, 'caller',   'Caller\n(API Gateway,\nSDK, CLI)', 'gray')
    n(g, 'lambda',   'Lambda\nFunction', 'navy')
    n(g, 'response', 'Response\nreturned\nto caller', 'green')
    n(g, 'event_src','Event Source\n(S3, SNS,\nEventBridge)', 'gold')
    n(g, 'queue',    'Internal\nEvent Queue\n(managed by Lambda)', 'teal')
    n(g, 'dlq',      'Dead Letter\nQueue (DLQ)\non failure', 'red')
    n(g, 'stream',   'Stream Source\n(Kinesis, DynamoDB\nStreams, SQS)', 'purple')
    n(g, 'batch',    'Lambda polls\nbatch of records', 'navy')
    e(g, 'caller',   'lambda',   'sync: waits\nfor result')
    e(g, 'lambda',   'response', '')
    e(g, 'event_src','queue',    'async: fire-\nand-forget')
    e(g, 'queue',    'lambda',   'retries\n0–2x')
    e(g, 'lambda',   'dlq',      'all retries\nfailed', '#ef4444', 'dashed')
    e(g, 'stream',   'batch',    'polling\n(bisect on error)')
    e(g, 'batch',    'lambda',   '')
    g.render(os.path.join(OUT, 'aws-lambda-invocation'), cleanup=True)


def diag_lambda_cold_start():
    g = base_graph('lambda_cold_start', 'Lambda Cold Start vs Warm Invocation', rankdir='TB')
    with g.subgraph(name='cluster_cold') as c:
        c.attr(label='Cold Start (first invocation)', style='filled', fillcolor='#fee2e2',
               color='#ef4444', fontcolor='#991b1b', fontname='Helvetica Neue Bold', fontsize='12')
        n(c, 'init_env',  'Init execution\nenvironment\n(~50–500 ms)', 'red')
        n(c, 'dl_pkg',    'Download\ndeployment package', 'red')
        n(c, 'init_rt',   'Initialize runtime\n+ imports', 'red')
        n(c, 'init_code', 'Run init code\n(outside handler)', 'gold')
        n(c, 'handler1',  'Execute\nhandler()', 'green')
        e(c, 'init_env',  'dl_pkg',    '')
        e(c, 'dl_pkg',    'init_rt',   '')
        e(c, 'init_rt',   'init_code', '')
        e(c, 'init_code', 'handler1',  '')
    with g.subgraph(name='cluster_warm') as w:
        w.attr(label='Warm Invocation (reused container)', style='filled', fillcolor='#dcfce7',
               color='#22c55e', fontcolor='#166534', fontname='Helvetica Neue Bold', fontsize='12')
        n(w, 'handler2', 'Execute\nhandler()\n(~1 ms overhead)', 'green')
    n(g, 'mitigations', 'Mitigations:\nProvisioned Concurrency\nSnapStart (Java)\nKeep-alive pings', 'teal')
    e(g, 'handler1',    'handler2',    'container\nreused', '#22c55e', 'dashed')
    e(g, 'mitigations', 'init_env',    'eliminates', '#14b8a6', 'dashed')
    g.render(os.path.join(OUT, 'aws-lambda-coldstart'), cleanup=True)


def diag_ecs_architecture():
    g = base_graph('ecs_arch', 'ECS Architecture — Cluster / Service / Task / Container')
    n(g, 'cluster',  'ECS Cluster\n(logical grouping)', 'gray')
    n(g, 'service',  'ECS Service\n(desired count,\nload balancer,\nauto-scaling)', 'navy')
    n(g, 'task_def', 'Task Definition\n(Docker image,\nCPU/mem,\nenv vars, IAM role)', 'purple')
    n(g, 'task',     'Running Task\n(1..N containers)', 'teal')
    n(g, 'ec2',      'Launch Type: EC2\n(you manage instances)', 'gold')
    n(g, 'fargate',  'Launch Type: Fargate\n(serverless — AWS\nmanages hosts)', 'green')
    n(g, 'alb',      'Application\nLoad Balancer', 'navy')
    n(g, 'ecr',      'ECR\n(container registry)', 'cyan')
    e(g, 'cluster',  'service',   'contains')
    e(g, 'service',  'task',      'schedules')
    e(g, 'task_def', 'task',      'instantiated as')
    e(g, 'ecr',      'task',      'pulls image')
    e(g, 'task',     'ec2',       'runs on', '#f59e0b')
    e(g, 'task',     'fargate',   'runs on', '#22c55e')
    e(g, 'alb',      'service',   'routes traffic')
    g.render(os.path.join(OUT, 'aws-ecs-architecture'), cleanup=True)


def diag_ecs_vs_fargate():
    g = base_graph('ecs_vs_fargate', 'ECS EC2 vs Fargate — Responsibility Model', rankdir='TB')
    with g.subgraph(name='cluster_ec2') as c:
        c.attr(label='ECS on EC2 — you manage', style='filled', fillcolor='#fef3c7',
               color='#f59e0b', fontcolor='#92400e', fontname='Helvetica Neue Bold', fontsize='12')
        n(c, 'ec2_patch', 'OS patching\n+ AMI updates', 'gold')
        n(c, 'ec2_cap',   'Capacity planning\n+ ASG', 'gold')
        n(c, 'ec2_eni',   'ENI / network\nconfiguration', 'gold')
        n(c, 'ec2_task2', 'Task placement\nstrategy', 'gold')
    with g.subgraph(name='cluster_fg') as f:
        f.attr(label='Fargate — AWS manages', style='filled', fillcolor='#dcfce7',
               color='#22c55e', fontcolor='#166534', fontname='Helvetica Neue Bold', fontsize='12')
        n(f, 'fg_host',  'Host provisioning\n+ isolation', 'green')
        n(f, 'fg_patch', 'OS/kernel patching', 'green')
        n(f, 'fg_net',   'Networking\n(vpcCNI)', 'green')
    n(g, 'shared', 'Both: Task Definition,\nService, IAM roles,\nCloudWatch Logs', 'navy')
    e(g, 'shared', 'ec2_task2', '', '#f59e0b', 'dashed')
    e(g, 'shared', 'fg_host',  '', '#22c55e', 'dashed')
    g.render(os.path.join(OUT, 'aws-ecs-vs-fargate'), cleanup=True)


def diag_eks_architecture():
    g = base_graph('eks_arch', 'EKS Architecture — Control Plane + Data Plane')
    n(g, 'api_srv',  'kube-apiserver\n(AWS-managed,\nmulti-AZ)', 'navy')
    n(g, 'etcd',     'etcd\n(AWS-managed)', 'navy')
    n(g, 'sched',    'kube-scheduler\ncontroller-manager', 'navy')
    n(g, 'ng_ec2',   'Managed Node Group\n(EC2 Auto Scaling)', 'gold')
    n(g, 'fargate',  'Fargate Profile\n(serverless pods)', 'green')
    n(g, 'kubelet',  'kubelet + kube-proxy\non each node', 'teal')
    n(g, 'pod',      'Pod\n(1+ containers)', 'purple')
    n(g, 'vpc_cni',  'VPC CNI\n(pod gets VPC IP)', 'cyan')
    n(g, 'alb_ctrl', 'AWS LB Controller\n(ALB per Ingress)', 'navy')
    n(g, 'ebs_csi',  'EBS / EFS CSI\n(persistent volumes)', 'gray')
    e(g, 'api_srv',  'etcd',     'state store')
    e(g, 'api_srv',  'sched',    '')
    e(g, 'api_srv',  'kubelet',  'watches')
    e(g, 'kubelet',  'pod',      'runs')
    e(g, 'ng_ec2',   'kubelet',  'hosts')
    e(g, 'fargate',  'pod',      'serverless\nhost')
    e(g, 'vpc_cni',  'pod',      'assigns IP')
    e(g, 'alb_ctrl', 'api_srv',  'reconciles\nIngress', '#3b82f6')
    e(g, 'ebs_csi',  'pod',      'mounts PV', '#6b7280', 'dashed')
    g.render(os.path.join(OUT, 'aws-eks-architecture'), cleanup=True)


def diag_eks_networking():
    g = base_graph('eks_networking', 'EKS Networking — VPC CNI + Services + Ingress', rankdir='TB')
    n(g, 'inet',    'Internet', 'gray')
    n(g, 'alb',     'ALB (Ingress)\npublic subnet', 'navy')
    n(g, 'svc',     'ClusterIP Service\n(kube-proxy rules)', 'teal')
    n(g, 'pod_a',   'Pod A\n10.0.1.15\n(VPC IP)', 'purple')
    n(g, 'pod_b',   'Pod B\n10.0.2.22\n(VPC IP)', 'purple')
    n(g, 'sg_pod',  'Security Group\nfor Pods\n(per-pod SG)', 'gold')
    n(g, 'rds',     'RDS / ElastiCache\n(private subnet)', 'green')
    e(g, 'inet',   'alb',    'HTTPS')
    e(g, 'alb',    'svc',    'path-based\nrouting')
    e(g, 'svc',    'pod_a',  '')
    e(g, 'svc',    'pod_b',  '')
    e(g, 'sg_pod', 'pod_a',  'enforces', '#f59e0b', 'dashed')
    e(g, 'sg_pod', 'pod_b',  'enforces', '#f59e0b', 'dashed')
    e(g, 'pod_a',  'rds',    'private\nrouting', '#22c55e')
    e(g, 'pod_b',  'rds',    'private\nrouting', '#22c55e')
    g.render(os.path.join(OUT, 'aws-eks-networking'), cleanup=True)


def diag_s3_storage_classes():
    g = base_graph('s3_storage_classes', 'S3 Storage Classes — Cost vs Access Latency', rankdir='TB')
    n(g, 'std',      'S3 Standard\n99.99% avail\nFrequent access\nHighest cost/GB', 'green')
    n(g, 'ia',       'S3 Standard-IA\nInfrequent access\nRetrieval fee\n128KB min object', 'navy')
    n(g, 'one_ia',   'S3 One Zone-IA\nSingle AZ\nCheaper IA\n20% lower cost', 'teal')
    n(g, 'intl',     'S3 Intelligent-Tiering\nAuto-moves objects\nbetween tiers\nSmall monitoring fee', 'purple')
    n(g, 'glacier_i','Glacier Instant\nArchive + instant\nretrieval (<ms)', 'gold')
    n(g, 'glacier_f','Glacier Flexible\n1–12 hr retrieval\nLowest archive cost', 'gold')
    n(g, 'deep',     'Glacier Deep Archive\n12–48 hr retrieval\nLowest cost of all', 'red')
    e(g, 'std',   'ia',       'Lifecycle rule\n(30+ days)', '#3b82f6')
    e(g, 'ia',    'one_ia',   'single-AZ\noptimization')
    e(g, 'ia',    'glacier_i','archive\nfrequency drops')
    e(g, 'glacier_i','glacier_f','even less\nfrequent', '#f59e0b')
    e(g, 'glacier_f','deep',  'long-term\nretention', '#ef4444')
    e(g, 'std',   'intl',     'auto-tiering\nalternative', '#6366f1', 'dashed')
    g.render(os.path.join(OUT, 'aws-s3-storage-classes'), cleanup=True)


def diag_s3_event_flow():
    g = base_graph('s3_event_flow', 'S3 Event-Driven Architecture — Notifications + Triggers')
    n(g, 'client',  'Client\n(browser / app\n/ SDK)', 'gray')
    n(g, 's3',      'S3 Bucket\n(source)', 'navy')
    n(g, 'sns',     'SNS Topic\n(fan-out)', 'gold')
    n(g, 'sqs',     'SQS Queue\n(durable buffer)', 'teal')
    n(g, 'lambda',  'Lambda\n(real-time\nprocessing)', 'purple')
    n(g, 'eb',      'EventBridge\n(complex routing\nrules)', 'cyan')
    n(g, 'etl',     'ETL / Glue\nor Batch job', 'green')
    n(g, 'notify',  'Email / SMS\nalert', 'green')
    e(g, 'client',  's3',     'PutObject')
    e(g, 's3',      'sns',    's3:ObjectCreated\nevent')
    e(g, 's3',      'sqs',    'direct SQS\nnotification')
    e(g, 's3',      'lambda', 'direct trigger')
    e(g, 's3',      'eb',     'EventBridge\nintegration')
    e(g, 'sns',     'lambda', 'fan-out', '#6366f1')
    e(g, 'sns',     'notify', 'alert', '#22c55e')
    e(g, 'sqs',     'etl',    'batch\nprocessing', '#14b8a6')
    g.render(os.path.join(OUT, 'aws-s3-event-flow'), cleanup=True)


def diag_iam_model():
    g = base_graph('iam_model', 'IAM Authorization Model — Principal / Policy / Resource', rankdir='TB')
    n(g, 'principal', 'Principal\n(IAM User, Role,\nFederated Identity,\nAWS Service)', 'navy')
    n(g, 'auth_req',  'Authorization\nRequest\n(action + resource\n+ condition)', 'gray')
    n(g, 'policy',    'IAM Policy\n(JSON: Effect Allow/Deny\nAction, Resource,\nCondition)', 'purple')
    n(g, 'scp',       'SCP (Org)\nMax permissions\nfor entire OU', 'red')
    n(g, 'perm_bdy',  'Permissions Boundary\nMax permissions\nfor IAM entity', 'gold')
    n(g, 'resource',  'AWS Resource\n(S3 bucket, EC2,\nDynamoDB table…)', 'teal')
    n(g, 'allow',     'Allow\nRequest proceeds', 'green')
    n(g, 'deny',      'Deny\n(explicit deny wins\nover any Allow)', 'red')
    e(g, 'principal', 'auth_req',  'makes')
    e(g, 'auth_req',  'policy',    'evaluated against')
    e(g, 'scp',       'policy',    'limits', '#ef4444', 'dashed')
    e(g, 'perm_bdy',  'policy',    'limits', '#f59e0b', 'dashed')
    e(g, 'policy',    'allow',     'Effect: Allow\nno Deny present', '#22c55e')
    e(g, 'policy',    'deny',      'Effect: Deny\nor no Allow', '#ef4444')
    e(g, 'allow',     'resource',  'access granted')
    g.render(os.path.join(OUT, 'aws-iam-model'), cleanup=True)


def diag_iam_roles():
    g = base_graph('iam_roles', 'IAM Roles — Assume Role Flow (Cross-Account + EC2 + Lambda)')
    n(g, 'ec2',     'EC2 Instance\n(instance profile)', 'navy')
    n(g, 'lambda2', 'Lambda Function\n(execution role)', 'purple')
    n(g, 'dev',     'Developer\n(IAM User)', 'gray')
    n(g, 'sts',     'AWS STS\nsts:AssumeRole', 'gold')
    n(g, 'role',    'IAM Role\n(trust policy\n+ permission policy)', 'teal')
    n(g, 'creds',   'Temporary\nCredentials\n(15min–12hr)', 'green')
    n(g, 'target',  'Target Service\n(S3, DynamoDB,\ncross-account resource)', 'navy')
    e(g, 'ec2',     'sts',    'AssumeRole\nvia metadata')
    e(g, 'lambda2', 'sts',    'AssumeRole\nvia runtime')
    e(g, 'dev',     'sts',    'AssumeRole\n(MFA optional)')
    e(g, 'sts',     'role',   'validates\ntrust policy')
    e(g, 'role',    'creds',  'issues\ntemp creds')
    e(g, 'creds',   'target', 'access\nresource', '#22c55e')
    g.render(os.path.join(OUT, 'aws-iam-roles'), cleanup=True)


def diag_cloudwatch_pillars():
    g = base_graph('cw_pillars', 'CloudWatch — Metrics / Logs / Traces / Alarms / Events', rankdir='TB')
    n(g, 'src_ec2',   'EC2 / ECS / EKS\n(CloudWatch Agent)', 'gray')
    n(g, 'src_lambda','Lambda\n(built-in integration)', 'gray')
    n(g, 'src_app',   'Application\n(SDK / EMF)', 'gray')
    n(g, 'metrics',   'Metrics\n(numeric time series\n1-min / 1-sec granularity)', 'navy')
    n(g, 'logs',      'Logs\n(Log Groups /\nLog Streams\nInsights queries)', 'teal')
    n(g, 'traces',    'X-Ray Traces\n(distributed tracing\nservice map)', 'purple')
    n(g, 'alarm',     'CloudWatch Alarm\n(threshold /\nAnomaly Detection)', 'gold')
    n(g, 'dash',      'Dashboards\n(cross-account /\ncross-region)', 'cyan')
    n(g, 'action',    'Actions\n(SNS / Auto Scaling\n/ EC2 action)', 'green')
    n(g, 'events',    'EventBridge\n(scheduled rules\n+ event patterns)', 'navy')
    e(g, 'src_ec2',   'metrics', '')
    e(g, 'src_ec2',   'logs',    '')
    e(g, 'src_lambda','metrics', '')
    e(g, 'src_lambda','logs',    '')
    e(g, 'src_lambda','traces',  '')
    e(g, 'src_app',   'metrics', 'EMF JSON')
    e(g, 'src_app',   'logs',    '')
    e(g, 'metrics',   'alarm',   'threshold\nbreach')
    e(g, 'alarm',     'action',  'trigger', '#22c55e')
    e(g, 'metrics',   'dash',    '')
    e(g, 'logs',      'dash',    '')
    e(g, 'events',    'action',  'schedule /\npattern', '#3b82f6')
    g.render(os.path.join(OUT, 'aws-cloudwatch-pillars'), cleanup=True)


def diag_cloudwatch_alarm_flow():
    g = base_graph('cw_alarm', 'CloudWatch Alarm States and Auto-Scaling Response')
    n(g, 'metric',   'CPUUtilization\nmetric\n(5-min period)', 'navy')
    n(g, 'ok',       'State: OK\n< 70%', 'green')
    n(g, 'alarm',    'State: ALARM\n>= 70% for 3\nconsecutive periods', 'red')
    n(g, 'insuf',    'State: INSUFFICIENT_DATA\n(no data points)', 'gray')
    n(g, 'sns',      'SNS → PagerDuty\n/ email alert', 'gold')
    n(g, 'asg',      'Auto Scaling\nscale-out policy\n(+2 instances)', 'teal')
    n(g, 'scale_in', 'Scale-in policy\n(–1 instance)\nafter cooldown', 'green')
    e(g, 'metric',   'ok',      'within\nthreshold')
    e(g, 'metric',   'alarm',   'breach\nthreshold', '#ef4444')
    e(g, 'metric',   'insuf',   'no data', '#6b7280')
    e(g, 'alarm',    'sns',     'notify', '#f59e0b')
    e(g, 'alarm',    'asg',     'scale-out\naction', '#14b8a6')
    e(g, 'asg',      'scale_in','after cooldown\n(300s default)', '#22c55e')
    e(g, 'scale_in', 'ok',      'metric drops\nbelow threshold', '#22c55e')
    g.render(os.path.join(OUT, 'aws-cloudwatch-alarm'), cleanup=True)


def diag_sqs_architecture():
    g = base_graph('sqs_arch', 'SQS — Standard vs FIFO Queue Architecture')
    n(g, 'producer', 'Producer\n(Lambda / EC2\n/ API Gateway)', 'gray')
    n(g, 'std_q',    'Standard Queue\n- At-least-once\n- Best-effort order\n- Nearly unlimited TPS', 'navy')
    n(g, 'fifo_q',   'FIFO Queue\n- Exactly-once\n- Strict order\n- 3,000 msg/s (batched)', 'purple')
    n(g, 'consumer', 'Consumer\n(Lambda / EC2\nscaled by queue depth)', 'teal')
    n(g, 'dlq',      'Dead Letter Queue\n(maxReceiveCount\nexceeded)', 'red')
    n(g, 'visibility','Visibility Timeout\n(msg hidden from\nother consumers\nduring processing)', 'gold')
    e(g, 'producer', 'std_q',    'SendMessage')
    e(g, 'producer', 'fifo_q',   'SendMessage\n+ MessageGroupId')
    e(g, 'std_q',    'consumer', 'ReceiveMessage\n(long poll)')
    e(g, 'fifo_q',   'consumer', 'ReceiveMessage\n(ordered)')
    e(g, 'std_q',    'visibility','hides msg\nafter receive', '#f59e0b', 'dashed')
    e(g, 'consumer', 'std_q',    'DeleteMessage\n(ack success)', '#22c55e')
    e(g, 'std_q',    'dlq',      'retry exhausted', '#ef4444')
    e(g, 'fifo_q',   'dlq',      'retry exhausted', '#ef4444')
    g.render(os.path.join(OUT, 'aws-sqs-architecture'), cleanup=True)


def diag_sqs_vs_sns():
    g = base_graph('sqs_vs_sns', 'SQS vs SNS — Pull vs Push, Fan-out Pattern', rankdir='TB')
    n(g, 'pub',    'Publisher\n(event source)', 'gray')
    n(g, 'sns',    'SNS Topic\n(push / fan-out\nno persistence)', 'gold')
    n(g, 'sqs_a',  'SQS Queue A\n(pull / durable\nbuffer)', 'navy')
    n(g, 'sqs_b',  'SQS Queue B\n(pull / durable\nbuffer)', 'navy')
    n(g, 'lambda', 'Lambda\n(direct SNS\nsubscription)', 'purple')
    n(g, 'email',  'Email / HTTP\nendpoint', 'teal')
    n(g, 'worker_a','Worker Pool A\n(polling SQS A)', 'green')
    n(g, 'worker_b','Worker Pool B\n(polling SQS B)', 'green')
    e(g, 'pub',    'sns',      'Publish')
    e(g, 'sns',    'sqs_a',    'fan-out')
    e(g, 'sns',    'sqs_b',    'fan-out')
    e(g, 'sns',    'lambda',   'push')
    e(g, 'sns',    'email',    'push')
    e(g, 'sqs_a',  'worker_a', 'long\npoll')
    e(g, 'sqs_b',  'worker_b', 'long\npoll')
    g.render(os.path.join(OUT, 'aws-sqs-vs-sns'), cleanup=True)


def diag_sns_fanout():
    g = base_graph('sns_fanout', 'SNS Fan-out Topology — Topic + Subscriptions')
    n(g, 'publisher', 'Publisher\n(any AWS service\nor SDK client)', 'gray')
    n(g, 'topic',     'SNS Topic\n(standard or FIFO)', 'gold')
    n(g, 'sqs1',      'SQS Queue\n(order processing)', 'navy')
    n(g, 'sqs2',      'SQS Queue\n(analytics pipeline)', 'navy')
    n(g, 'lambda',    'Lambda\n(real-time action)', 'purple')
    n(g, 'http',      'HTTP/S endpoint\n(webhook)', 'teal')
    n(g, 'email',     'Email subscription\n(ops alerts)', 'green')
    n(g, 'sms',       'SMS\n(mobile alert)', 'cyan')
    n(g, 'filter',    'Subscription Filter\nPolicy\n(route by attribute)', 'red')
    e(g, 'publisher', 'topic',   'Publish\n(with attributes)')
    e(g, 'topic',     'filter',  'applies\nfilters')
    e(g, 'filter',    'sqs1',    'matches\nOrderType=order', '#3b82f6')
    e(g, 'filter',    'sqs2',    'matches\nOrderType=analytics', '#3b82f6')
    e(g, 'filter',    'lambda',  'matches\nPriority=HIGH', '#6366f1')
    e(g, 'topic',     'http',    'no filter')
    e(g, 'topic',     'email',   'no filter')
    e(g, 'topic',     'sms',     'no filter')
    g.render(os.path.join(OUT, 'aws-sns-fanout'), cleanup=True)


def diag_kinesis_architecture():
    g = base_graph('kinesis_arch', 'Kinesis Data Streams — Shards, Producers, Consumers')
    n(g, 'prod_a',  'Producer A\n(web clickstream)', 'gray')
    n(g, 'prod_b',  'Producer B\n(IoT sensor)', 'gray')
    n(g, 'prod_c',  'Producer C\n(app logs / KPL)', 'gray')
    n(g, 'shard1',  'Shard 1\n1 MB/s in\n2 MB/s out\nRetention: 24h–365d', 'navy')
    n(g, 'shard2',  'Shard 2\n(partition key\ndetermines shard)', 'navy')
    n(g, 'shard3',  'Shard 3', 'navy')
    n(g, 'kcl',     'KCL App\n(EFO consumer\nenhanced fan-out\n2 MB/s per consumer)', 'purple')
    n(g, 'lambda',  'Lambda\n(event source\nmapping)', 'teal')
    n(g, 'firehose','Kinesis Firehose\n(S3 / Redshift\nbuffered delivery)', 'gold')
    n(g, 'analytics','Kinesis Data Analytics\n(Apache Flink\nSQL on stream)', 'cyan')
    e(g, 'prod_a',  'shard1',    'PutRecord\npartitionKey')
    e(g, 'prod_b',  'shard2',    'PutRecord')
    e(g, 'prod_c',  'shard3',    'PutRecords\n(batch)')
    e(g, 'shard1',  'kcl',       'GetRecords\nor EFO')
    e(g, 'shard2',  'lambda',    'polling\nor EFO')
    e(g, 'shard3',  'firehose',  'auto-\ndelivery')
    e(g, 'shard1',  'analytics', 'SQL\nwindow')
    e(g, 'firehose','analytics', '', '#f59e0b', 'dashed')
    g.render(os.path.join(OUT, 'aws-kinesis-architecture'), cleanup=True)


def diag_kinesis_vs_sqs():
    g = base_graph('kinesis_vs_sqs', 'Kinesis Streams vs SQS — When to Use Each', rankdir='TB')
    with g.subgraph(name='cluster_kinesis') as k:
        k.attr(label='Kinesis Data Streams — choose when:', style='filled',
               fillcolor='#dbeafe', color='#3b82f6', fontcolor='#1e40af',
               fontname='Helvetica Neue Bold', fontsize='12')
        n(k, 'k1', 'Multiple consumers\nread same records\n(replay)', 'navy')
        n(k, 'k2', 'Ordered within\npartition key', 'navy')
        n(k, 'k3', 'High-throughput\n(>10k msg/s)', 'navy')
        n(k, 'k4', 'Time-series /\nlog aggregation', 'navy')
    with g.subgraph(name='cluster_sqs') as s:
        s.attr(label='SQS — choose when:', style='filled',
               fillcolor='#f3f4f6', color='#6b7280', fontcolor='#374151',
               fontname='Helvetica Neue Bold', fontsize='12')
        n(s, 's1', 'Task queue\n(one consumer\nper message)', 'gray')
        n(s, 's2', 'Message deleted\nafter processing', 'gray')
        n(s, 's3', 'Variable\nthroughput needs', 'gray')
        n(s, 's4', 'DLQ + visibility\ntimeout pattern', 'gray')
    g.render(os.path.join(OUT, 'aws-kinesis-vs-sqs'), cleanup=True)


def diag_rds_ha():
    g = base_graph('rds_ha', 'RDS Multi-AZ — High Availability + Failover')
    n(g, 'app',       'Application\n(EC2 / Lambda\n/ ECS task)', 'gray')
    n(g, 'endpoint',  'RDS Endpoint\n(DNS-based\nno IP change)', 'navy')
    n(g, 'primary',   'Primary DB\n(AZ-a)\n(reads + writes)', 'green')
    n(g, 'standby',   'Standby DB\n(AZ-b)\n(synchronous\nreplication)', 'teal')
    n(g, 'ro1',       'Read Replica 1\n(async replication\nfor read scale)', 'cyan')
    n(g, 'ro2',       'Read Replica 2\n(cross-region\ndisaster recovery)', 'purple')
    n(g, 'failover',  'Automatic Failover\n60–120 sec\nStandby promoted\nDNS updated', 'gold')
    e(g, 'app',       'endpoint',  'connect')
    e(g, 'endpoint',  'primary',   'normal\noperation')
    e(g, 'primary',   'standby',   'sync\nreplication')
    e(g, 'primary',   'ro1',       'async\nreplication')
    e(g, 'primary',   'ro2',       'async cross-\nregion rep')
    e(g, 'primary',   'failover',  'AZ failure', '#ef4444')
    e(g, 'failover',  'standby',   'promote\nstandby', '#22c55e')
    e(g, 'app',       'ro1',       'read-only\nqueries', '#06b6d4', 'dashed')
    g.render(os.path.join(OUT, 'aws-rds-ha'), cleanup=True)


def diag_rds_vs_aurora():
    g = base_graph('rds_vs_aurora', 'RDS vs Aurora — Architecture Differences', rankdir='TB')
    with g.subgraph(name='cluster_rds') as r:
        r.attr(label='RDS (MySQL / Postgres / Oracle…)', style='filled', fillcolor='#dbeafe',
               color='#3b82f6', fontcolor='#1e40af', fontname='Helvetica Neue Bold', fontsize='12')
        n(r, 'rds_p',  'Primary instance\n(1 EBS volume\nper AZ)', 'navy')
        n(r, 'rds_s',  'Standby instance\n(block-level\nsync rep)', 'teal')
        n(r, 'rds_ebs','EBS storage\n(replicated within\none AZ)', 'gray')
    with g.subgraph(name='cluster_aurora') as a:
        a.attr(label='Aurora (MySQL/Postgres-compatible)', style='filled', fillcolor='#dcfce7',
               color='#22c55e', fontcolor='#166534', fontname='Helvetica Neue Bold', fontsize='12')
        n(a, 'aur_w',  'Writer instance', 'green')
        n(a, 'aur_r1', 'Reader 1 (AZ-b)', 'green')
        n(a, 'aur_r2', 'Reader 2 (AZ-c)', 'green')
        n(a, 'aur_vol','Shared cluster volume\n6 copies across\n3 AZs (10GB auto-grow)', 'teal')
    e(r, 'rds_p',  'rds_s',   'sync block\nreplication')
    e(r, 'rds_p',  'rds_ebs', '')
    e(a, 'aur_w',  'aur_vol', 'writes')
    e(a, 'aur_r1', 'aur_vol', 'reads')
    e(a, 'aur_r2', 'aur_vol', 'reads')
    g.render(os.path.join(OUT, 'aws-rds-vs-aurora'), cleanup=True)


def diag_dynamodb_data_model():
    g = base_graph('ddb_model', 'DynamoDB Data Model — Partition Key, Sort Key, GSI', rankdir='TB')
    n(g, 'table',    'Table\n(Orders)', 'navy')
    n(g, 'pk',       'Partition Key\n(PK = userId)\nhash → shard', 'purple')
    n(g, 'sk',       'Sort Key\n(SK = orderId#timestamp)\nrange queries within PK', 'teal')
    n(g, 'item',     'Item\n{userId, orderId,\nstatus, totalAmount,\ncreatedAt, …}', 'gray')
    n(g, 'lsi',      'LSI (Local)\nSame PK\nDiff sort key\n(same partition)', 'gold')
    n(g, 'gsi',      'GSI (Global)\nNew PK + SK\nacross all items\n(async replica)', 'green')
    n(g, 'query_pk', 'Query: PK=userId123\nall orders for user', 'cyan')
    n(g, 'query_gsi','Query GSI: status=SHIPPED\nall shipped orders', 'cyan')
    e(g, 'table',    'pk',       'partition by')
    e(g, 'pk',       'sk',       'sorted by\n(optional)')
    e(g, 'pk',       'item',     'contains')
    e(g, 'sk',       'item',     'orders within')
    e(g, 'table',    'lsi',      'projected\nattributes', '#f59e0b')
    e(g, 'table',    'gsi',      'async\nreplica', '#22c55e')
    e(g, 'query_pk', 'pk',       'uses base\ntable')
    e(g, 'query_gsi','gsi',      'uses GSI')
    g.render(os.path.join(OUT, 'aws-dynamodb-data-model'), cleanup=True)


def diag_dynamodb_capacity():
    g = base_graph('ddb_capacity', 'DynamoDB Capacity Modes — On-Demand vs Provisioned + DAX')
    n(g, 'app',        'Application\n(read-heavy\nworkload)', 'gray')
    n(g, 'dax',        'DAX Cluster\n(in-memory cache\n<1 ms reads\nwrite-through)', 'purple')
    n(g, 'ddb',        'DynamoDB Table', 'navy')
    n(g, 'on_demand',  'On-Demand Mode\nAuto-scales\nPay per request\nUp to 40K RCU/WCU', 'gold')
    n(g, 'provisioned','Provisioned Mode\nSet RCU/WCU\nAuto Scaling policy\n30% cheaper at steady state', 'green')
    n(g, 'burst',      'Burst Capacity\n5-min reserve\nper partition', 'teal')
    n(g, 'hot_part',   'Hot Partition\n(design flaw)\nthrottle risk', 'red')
    e(g, 'app',        'dax',        'cache-aside\nreads', '#6366f1')
    e(g, 'dax',        'ddb',        'cache miss\n+ all writes')
    e(g, 'ddb',        'on_demand',  'traffic\nunpredictable')
    e(g, 'ddb',        'provisioned','traffic\nsteady-state')
    e(g, 'provisioned','burst',      'absorbs\nspikes', '#14b8a6')
    e(g, 'provisioned','hot_part',   'poor key\ndesign', '#ef4444', 'dashed')
    g.render(os.path.join(OUT, 'aws-dynamodb-capacity'), cleanup=True)


def diag_cloudformation_lifecycle():
    g = base_graph('cfn_lifecycle', 'CloudFormation Stack Lifecycle — Create / Update / Delete', rankdir='TB')
    n(g, 'template',  'CloudFormation\nTemplate (YAML/JSON)\nResources, Parameters,\nOutputs, Mappings', 'navy')
    n(g, 'change_set','Change Set\n(preview diffs\nbefore apply)', 'gold')
    n(g, 'stack',     'Stack\n(logical grouping\nof resources)', 'teal')
    n(g, 'resources', 'AWS Resources\n(EC2, VPC, RDS,\nLambda, IAM…)', 'green')
    n(g, 'rollback',  'Rollback\n(on any resource\ncreation failure)', 'red')
    n(g, 'drift',     'Drift Detection\n(detect manual\nchanges out-of-band)', 'purple')
    n(g, 'stackset',  'StackSets\n(deploy across\nmultiple accounts\n+ regions)', 'cyan')
    e(g, 'template',  'change_set','create-change-set')
    e(g, 'change_set','stack',     'execute\nchange set')
    e(g, 'template',  'stack',     'create-stack\nor update-stack')
    e(g, 'stack',     'resources', 'provisions\n+ manages')
    e(g, 'stack',     'rollback',  'failure', '#ef4444')
    e(g, 'rollback',  'resources', 'restore\nprevious state', '#ef4444')
    e(g, 'stack',     'drift',     'detect\nmanual changes', '#6366f1', 'dashed')
    e(g, 'template',  'stackset',  'multi-account\ndeployment', '#06b6d4', 'dashed')
    g.render(os.path.join(OUT, 'aws-cloudformation-lifecycle'), cleanup=True)


def diag_cloudformation_vs_cdk():
    g = base_graph('cfn_vs_cdk', 'CloudFormation vs CDK vs Terraform — IaC Comparison', rankdir='TB')
    n(g, 'cfn',    'CloudFormation\nYAML/JSON templates\nAWS-native\nNo extra tooling', 'navy')
    n(g, 'cdk',    'AWS CDK\nTypeScript/Python\nabstractions\nSynths to CFN', 'purple')
    n(g, 'tf',     'Terraform\nHCL / multi-cloud\nState file (S3+DynamoDB)\nLarge ecosystem', 'teal')
    n(g, 'sam',    'AWS SAM\nServerless-focused\nExtension of CFN\nLocal testing', 'gold')
    n(g, 'drift_risk','Risk: Drift\n(manual console\nchanges)', 'red')
    n(g, 'pick',   'Choose based on:\nTeam familiarity\nCloud portability\nAbstraction level', 'gray')
    e(g, 'cdk',    'cfn',      'synthesizes to\nCFN template')
    e(g, 'sam',    'cfn',      'extends CFN\nsyntax')
    e(g, 'cfn',    'drift_risk','if bypassed', '#ef4444', 'dashed')
    e(g, 'tf',     'drift_risk','if bypassed', '#ef4444', 'dashed')
    e(g, 'pick',   'cfn',      '', '#6b7280', 'dashed')
    e(g, 'pick',   'tf',       '', '#6b7280', 'dashed')
    e(g, 'pick',   'cdk',      '', '#6b7280', 'dashed')
    g.render(os.path.join(OUT, 'aws-cloudformation-vs-cdk'), cleanup=True)


def diag_codepipeline_flow():
    g = base_graph('codepipeline_flow', 'AWS CodePipeline — End-to-End CI/CD Stages')
    n(g, 'source',   'Source Stage\n(CodeCommit / GitHub\n/ S3 artifact)', 'gray')
    n(g, 'build',    'Build Stage\n(CodeBuild)\ndocker build,\nunit tests, lint', 'navy')
    n(g, 'test',     'Test Stage\n(CodeBuild / Lambda)\nintegration tests\nSonar scan', 'teal')
    n(g, 'approval', 'Manual Approval\nAction\n(SNS notification\nto reviewer)', 'gold')
    n(g, 'staging',  'Deploy: Staging\n(CodeDeploy / ECS\n/ CloudFormation)', 'purple')
    n(g, 'e2e',      'E2E Test Stage\n(Selenium / Cypress\ntest suite)', 'cyan')
    n(g, 'prod',     'Deploy: Production\nBlue/Green or\nRolling update', 'green')
    n(g, 'rollback', 'Auto Rollback\n(CloudWatch Alarm\nbreach)', 'red')
    e(g, 'source',   'build',    'commit\ntrigger')
    e(g, 'build',    'test',     'artifact')
    e(g, 'test',     'approval', 'tests passed')
    e(g, 'approval', 'staging',  'approved')
    e(g, 'staging',  'e2e',      '')
    e(g, 'e2e',      'prod',     'all passed')
    e(g, 'prod',     'rollback', 'error rate\nspike', '#ef4444')
    e(g, 'rollback', 'staging',  'revert to\nprevious', '#ef4444')
    g.render(os.path.join(OUT, 'aws-codepipeline-flow'), cleanup=True)


def diag_codepipeline_services():
    g = base_graph('codepipeline_svcs', 'AWS Developer Tools Suite — CodeCommit / Build / Deploy / Pipeline', rankdir='TB')
    n(g, 'cc',    'CodeCommit\n(Git repo\nAWS-native)', 'navy')
    n(g, 'cb',    'CodeBuild\n(managed build\ncontainers\npay-per-minute)', 'teal')
    n(g, 'cd',    'CodeDeploy\n(EC2 / Lambda\n/ ECS deployment\nstrategies)', 'purple')
    n(g, 'cp',    'CodePipeline\n(orchestrates\nall stages)', 'gold')
    n(g, 'ca',    'CodeArtifact\n(npm / Maven\n/ PyPI proxy\n+ private repo)', 'cyan')
    n(g, 's3art', 'S3 Artifact\nBucket\n(stage handoffs)', 'gray')
    n(g, 'ghub',  'GitHub / Bitbucket\n(CodeStar Connection)', 'gray')
    e(g, 'cp',    'cc',    'source action')
    e(g, 'cp',    'ghub',  'source action')
    e(g, 'cp',    'cb',    'build action')
    e(g, 'cp',    'cd',    'deploy action')
    e(g, 'cb',    's3art', 'output\nartifact')
    e(g, 's3art', 'cd',    'input\nartifact')
    e(g, 'cb',    'ca',    'pull deps\nfrom', '#06b6d4', 'dashed')
    g.render(os.path.join(OUT, 'aws-codepipeline-services'), cleanup=True)


def diag_vpc_architecture():
    g = base_graph('vpc_arch', 'VPC Architecture — Subnets / Route Tables / Gateways', rankdir='TB')
    n(g, 'internet',  'Internet', 'gray')
    n(g, 'igw',       'Internet Gateway\n(IGW)\npublic IPv4/IPv6', 'navy')
    n(g, 'pub_sub',   'Public Subnet\n(10.0.1.0/24)\nEC2 + ALB', 'green')
    n(g, 'priv_sub',  'Private Subnet\n(10.0.2.0/24)\nApp servers / ECS', 'teal')
    n(g, 'data_sub',  'Data Subnet\n(10.0.3.0/24)\nRDS / ElastiCache', 'purple')
    n(g, 'nat',       'NAT Gateway\n(in public subnet)\negress for private', 'gold')
    n(g, 'alb',       'ALB\n(public subnet)', 'navy')
    n(g, 'sg',        'Security Groups\n(stateful per ENI)', 'red')
    n(g, 'nacl',      'Network ACL\n(stateless per\nsubnet boundary)', 'red')
    n(g, 'vpc_ep',    'VPC Endpoints\n(Gateway: S3/DynamoDB\nInterface: most services)', 'cyan')
    e(g, 'internet',  'igw',       '')
    e(g, 'igw',       'pub_sub',   'route 0.0.0.0/0\n→ IGW')
    e(g, 'pub_sub',   'alb',       'ALB lives here')
    e(g, 'alb',       'priv_sub',  'forward to\napp servers')
    e(g, 'priv_sub',  'nat',       'egress to\ninternet', '#f59e0b')
    e(g, 'nat',       'igw',       '')
    e(g, 'priv_sub',  'data_sub',  'DB connections', '#8b5cf6')
    e(g, 'sg',        'priv_sub',  'instance-level\nfirewall', '#ef4444', 'dashed')
    e(g, 'nacl',      'priv_sub',  'subnet-level\nACL', '#ef4444', 'dashed')
    e(g, 'vpc_ep',    'priv_sub',  'private AWS\nAPI access', '#06b6d4', 'dashed')
    g.render(os.path.join(OUT, 'aws-vpc-architecture'), cleanup=True)


def diag_vpc_connectivity():
    g = base_graph('vpc_connectivity', 'VPC Connectivity Options — Peering / TGW / Direct Connect')
    n(g, 'vpc_a',    'VPC A\n(prod, 10.0.0.0/16)', 'navy')
    n(g, 'vpc_b',    'VPC B\n(dev, 10.1.0.0/16)', 'teal')
    n(g, 'vpc_c',    'VPC C\n(shared-svcs\n10.2.0.0/16)', 'purple')
    n(g, 'peer',     'VPC Peering\n(1-to-1, same region\nor cross-region)', 'green')
    n(g, 'tgw',      'Transit Gateway\n(hub-spoke\nhubs up to 5,000 VPCs)', 'gold')
    n(g, 'on_prem',  'On-Premises\nData Center', 'gray')
    n(g, 'vpn',      'Site-to-Site\nVPN (IPsec)', 'teal')
    n(g, 'dx',       'Direct Connect\n(private fiber\n1/10/100 Gbps)', 'cyan')
    e(g, 'vpc_a',    'peer',      '')
    e(g, 'vpc_b',    'peer',      '')
    e(g, 'vpc_a',    'tgw',       'attach')
    e(g, 'vpc_b',    'tgw',       'attach')
    e(g, 'vpc_c',    'tgw',       'attach')
    e(g, 'on_prem',  'vpn',       'IPsec tunnel')
    e(g, 'vpn',      'tgw',       'VPN attachment')
    e(g, 'on_prem',  'dx',        'dedicated\ncircuit')
    e(g, 'dx',       'tgw',       'DXGW\nattachment')
    g.render(os.path.join(OUT, 'aws-vpc-connectivity'), cleanup=True)


if __name__ == '__main__':
    diag_ec2_instance_lifecycle()
    diag_ec2_purchasing()
    diag_lambda_invocation()
    diag_lambda_cold_start()
    diag_ecs_architecture()
    diag_ecs_vs_fargate()
    diag_eks_architecture()
    diag_eks_networking()
    diag_s3_storage_classes()
    diag_s3_event_flow()
    diag_iam_model()
    diag_iam_roles()
    diag_cloudwatch_pillars()
    diag_cloudwatch_alarm_flow()
    diag_sqs_architecture()
    diag_sqs_vs_sns()
    diag_sns_fanout()
    diag_kinesis_architecture()
    diag_kinesis_vs_sqs()
    diag_rds_ha()
    diag_rds_vs_aurora()
    diag_dynamodb_data_model()
    diag_dynamodb_capacity()
    diag_cloudformation_lifecycle()
    diag_cloudformation_vs_cdk()
    diag_codepipeline_flow()
    diag_codepipeline_services()
    diag_vpc_architecture()
    diag_vpc_connectivity()
    print('All cloud diagrams generated.')
