#!/usr/bin/env python3
"""
Atomically rebuild diagram-manifests.ts from all research JSON files.
Run this after parallel generate jobs to fix race-condition overwrites.
"""
from __future__ import annotations
import json
from pathlib import Path

ROOT     = Path(__file__).resolve().parents[3]
RESEARCH = Path(__file__).resolve().parent / "research"
DIAGRAMS = ROOT / "apps" / "camora" / "public" / "diagrams"
MANIFEST = ROOT / "apps" / "camora" / "src" / "data" / "capra" / "topics" / "__generated" / "diagram-manifests.ts"

result: dict = {}

for jf in sorted(RESEARCH.glob("*.json")):
    try:
        data = json.loads(jf.read_text())
    except Exception:
        continue
    topic_id = data.get("topic_id", jf.stem)
    synthesis = data.get("synthesis", {})
    deep_dives = synthesis.get("deep_dives", [])
    tradeoffs  = synthesis.get("tradeoffs", [])

    topic_dir = DIAGRAMS / topic_id
    dd_entries = []
    for dd in deep_dives:
        png = f"deep-dive-{dd['id']}.png"
        if (topic_dir / png).exists():
            dd_entries.append({"id": dd["id"], "title": dd["title"], "file": png})

    tr_entries = []
    for tr in tradeoffs:
        png = f"tradeoff-{tr['id']}.png"
        if (topic_dir / png).exists():
            tr_entries.append({"id": tr["id"], "title": tr["title"], "file": png})

    if dd_entries or tr_entries:
        result[topic_id] = {"deepDives": dd_entries, "tradeoffs": tr_entries}

entries_ts = ""
for tid, data in sorted(result.items()):
    dd_json = json.dumps(data["deepDives"], indent=4)
    tr_json = json.dumps(data["tradeoffs"], indent=4)
    entries_ts += f"  '{tid}': {{\n    deepDives: {dd_json},\n    tradeoffs: {tr_json},\n  }},\n"

ts = f"""/* AUTO-GENERATED by apps/camora/scripts/research-topic.py --phase=generate.
   Do not edit by hand. Re-run the script to regenerate. */

type DiagramEntry = {{ id: string; title: string; file: string }};
type TopicDiagrams = {{ deepDives: DiagramEntry[]; tradeoffs: DiagramEntry[] }};

export const GENERATED_DIAGRAMS: Record<string, TopicDiagrams> = {{
{entries_ts}}};
"""

MANIFEST.write_text(ts, encoding="utf-8")
print(f"Manifest rebuilt: {len(result)} topics → {MANIFEST}")
for tid, d in sorted(result.items()):
    print(f"  {tid}: {len(d['deepDives'])} deep-dives, {len(d['tradeoffs'])} tradeoffs")
